window.municipios = [
  {
    "code_dpto":"5",
    "code":"5001",
    "name":"MEDELLÍN"
  },
  {
    "code_dpto":"5",
    "code":"5002",
    "name":"ABEJORRAL"
  },
  {
    "code_dpto":"5",
    "code":"5004",
    "name":"ABRIAQUÍ"
  },
  {
    "code_dpto":"5",
    "code":"5021",
    "name":"ALEJANDRÍA"
  },
  {
    "code_dpto":"5",
    "code":"5030",
    "name":"AMAGÁ"
  },
  {
    "code_dpto":"5",
    "code":"5031",
    "name":"AMALFI"
  },
  {
    "code_dpto":"5",
    "code":"5034",
    "name":"ANDES"
  },
  {
    "code_dpto":"5",
    "code":"5036",
    "name":"ANGELÓPOLIS"
  },
  {
    "code_dpto":"5",
    "code":"5038",
    "name":"ANGOSTURA"
  },
  {
    "code_dpto":"5",
    "code":"5040",
    "name":"ANORÍ"
  },
  {
    "code_dpto":"5",
    "code":"5042",
    "name":"SANTAFÉ DE ANTIOQUIA"
  },
  {
    "code_dpto":"5",
    "code":"5044",
    "name":"ANZA"
  },
  {
    "code_dpto":"5",
    "code":"5045",
    "name":"APARTADÓ"
  },
  {
    "code_dpto":"5",
    "code":"5051",
    "name":"ARBOLETES"
  },
  {
    "code_dpto":"5",
    "code":"5055",
    "name":"ARGELIA"
  },
  {
    "code_dpto":"5",
    "code":"5059",
    "name":"ARMENIA"
  },
  {
    "code_dpto":"5",
    "code":"5079",
    "name":"BARBOSA"
  },
  {
    "code_dpto":"5",
    "code":"5086",
    "name":"BELMIRA"
  },
  {
    "code_dpto":"5",
    "code":"5088",
    "name":"BELLO"
  },
  {
    "code_dpto":"5",
    "code":"5091",
    "name":"BETANIA"
  },
  {
    "code_dpto":"5",
    "code":"5093",
    "name":"BETULIA"
  },
  {
    "code_dpto":"5",
    "code":"5101",
    "name":"CIUDAD BOLÍVAR"
  },
  {
    "code_dpto":"5",
    "code":"5107",
    "name":"BRICEÑO"
  },
  {
    "code_dpto":"5",
    "code":"5113",
    "name":"BURITICÁ"
  },
  {
    "code_dpto":"5",
    "code":"5120",
    "name":"CÁCERES"
  },
  {
    "code_dpto":"5",
    "code":"5125",
    "name":"CAICEDO"
  },
  {
    "code_dpto":"5",
    "code":"5129",
    "name":"CALDAS"
  },
  {
    "code_dpto":"5",
    "code":"5134",
    "name":"CAMPAMENTO"
  },
  {
    "code_dpto":"5",
    "code":"5138",
    "name":"CAÑASGORDAS"
  },
  {
    "code_dpto":"5",
    "code":"5142",
    "name":"CARACOLÍ"
  },
  {
    "code_dpto":"5",
    "code":"5145",
    "name":"CARAMANTA"
  },
  {
    "code_dpto":"5",
    "code":"5147",
    "name":"CAREPA"
  },
  {
    "code_dpto":"5",
    "code":"5148",
    "name":"EL CARMEN DE VIBORAL"
  },
  {
    "code_dpto":"5",
    "code":"5150",
    "name":"CAROLINA"
  },
  {
    "code_dpto":"5",
    "code":"5154",
    "name":"CAUCASIA"
  },
  {
    "code_dpto":"5",
    "code":"5172",
    "name":"CHIGORODÓ"
  },
  {
    "code_dpto":"5",
    "code":"5190",
    "name":"CISNEROS"
  },
  {
    "code_dpto":"5",
    "code":"5197",
    "name":"COCORNÁ"
  },
  {
    "code_dpto":"5",
    "code":"5206",
    "name":"CONCEPCIÓN"
  },
  {
    "code_dpto":"5",
    "code":"5209",
    "name":"CONCORDIA"
  },
  {
    "code_dpto":"5",
    "code":"5212",
    "name":"COPACABANA"
  },
  {
    "code_dpto":"5",
    "code":"5234",
    "name":"DABEIBA"
  },
  {
    "code_dpto":"5",
    "code":"5237",
    "name":"DON MATÍAS"
  },
  {
    "code_dpto":"5",
    "code":"5240",
    "name":"EBÉJICO"
  },
  {
    "code_dpto":"5",
    "code":"5250",
    "name":"EL BAGRE"
  },
  {
    "code_dpto":"5",
    "code":"5264",
    "name":"ENTRERRIOS"
  },
  {
    "code_dpto":"5",
    "code":"5266",
    "name":"ENVIGADO"
  },
  {
    "code_dpto":"5",
    "code":"5282",
    "name":"FREDONIA"
  },
  {
    "code_dpto":"5",
    "code":"5284",
    "name":"FRONTINO"
  },
  {
    "code_dpto":"5",
    "code":"5306",
    "name":"GIRALDO"
  },
  {
    "code_dpto":"5",
    "code":"5308",
    "name":"GIRARDOTA"
  },
  {
    "code_dpto":"5",
    "code":"5310",
    "name":"GÓMEZ PLATA"
  },
  {
    "code_dpto":"5",
    "code":"5313",
    "name":"GRANADA"
  },
  {
    "code_dpto":"5",
    "code":"5315",
    "name":"GUADALUPE"
  },
  {
    "code_dpto":"5",
    "code":"5318",
    "name":"GUARNE"
  },
  {
    "code_dpto":"5",
    "code":"5321",
    "name":"GUATAPE"
  },
  {
    "code_dpto":"5",
    "code":"5347",
    "name":"HELICONIA"
  },
  {
    "code_dpto":"5",
    "code":"5353",
    "name":"HISPANIA"
  },
  {
    "code_dpto":"5",
    "code":"5360",
    "name":"ITAGUI"
  },
  {
    "code_dpto":"5",
    "code":"5361",
    "name":"ITUANGO"
  },
  {
    "code_dpto":"5",
    "code":"5364",
    "name":"JARDÍN"
  },
  {
    "code_dpto":"5",
    "code":"5368",
    "name":"JERICÓ"
  },
  {
    "code_dpto":"5",
    "code":"5376",
    "name":"LA CEJA"
  },
  {
    "code_dpto":"5",
    "code":"5380",
    "name":"LA ESTRELLA"
  },
  {
    "code_dpto":"5",
    "code":"5390",
    "name":"LA PINTADA"
  },
  {
    "code_dpto":"5",
    "code":"5400",
    "name":"LA UNIÓN"
  },
  {
    "code_dpto":"5",
    "code":"5411",
    "name":"LIBORINA"
  },
  {
    "code_dpto":"5",
    "code":"5425",
    "name":"MACEO"
  },
  {
    "code_dpto":"5",
    "code":"5440",
    "name":"MARINILLA"
  },
  {
    "code_dpto":"5",
    "code":"5467",
    "name":"MONTEBELLO"
  },
  {
    "code_dpto":"5",
    "code":"5475",
    "name":"MURINDÓ"
  },
  {
    "code_dpto":"5",
    "code":"5480",
    "name":"MUTATÁ"
  },
  {
    "code_dpto":"5",
    "code":"5483",
    "name":"NARIÑO"
  },
  {
    "code_dpto":"5",
    "code":"5490",
    "name":"NECOCLÍ"
  },
  {
    "code_dpto":"5",
    "code":"5495",
    "name":"NECHÍ"
  },
  {
    "code_dpto":"5",
    "code":"5501",
    "name":"OLAYA"
  },
  {
    "code_dpto":"5",
    "code":"5541",
    "name":"PEÑOL"
  },
  {
    "code_dpto":"5",
    "code":"5543",
    "name":"PEQUE"
  },
  {
    "code_dpto":"5",
    "code":"5576",
    "name":"PUEBLORRICO"
  },
  {
    "code_dpto":"5",
    "code":"5579",
    "name":"PUERTO BERRÍO"
  },
  {
    "code_dpto":"5",
    "code":"5585",
    "name":"PUERTO NARE"
  },
  {
    "code_dpto":"5",
    "code":"5591",
    "name":"PUERTO TRIUNFO"
  },
  {
    "code_dpto":"5",
    "code":"5604",
    "name":"REMEDIOS"
  },
  {
    "code_dpto":"5",
    "code":"5607",
    "name":"RETIRO"
  },
  {
    "code_dpto":"5",
    "code":"5615",
    "name":"RIONEGRO"
  },
  {
    "code_dpto":"5",
    "code":"5628",
    "name":"SABANALARGA"
  },
  {
    "code_dpto":"5",
    "code":"5631",
    "name":"SABANETA"
  },
  {
    "code_dpto":"5",
    "code":"5642",
    "name":"SALGAR"
  },
  {
    "code_dpto":"5",
    "code":"5647",
    "name":"SAN ANDRÉS DE CUERQUÍA"
  },
  {
    "code_dpto":"5",
    "code":"5649",
    "name":"SAN CARLOS"
  },
  {
    "code_dpto":"5",
    "code":"5652",
    "name":"SAN FRANCISCO"
  },
  {
    "code_dpto":"5",
    "code":"5656",
    "name":"SAN JERÓNIMO"
  },
  {
    "code_dpto":"5",
    "code":"5658",
    "name":"SAN JOSÉ DE LA MONTAÑA"
  },
  {
    "code_dpto":"5",
    "code":"5659",
    "name":"SAN JUAN DE URABÁ"
  },
  {
    "code_dpto":"5",
    "code":"5660",
    "name":"SAN LUIS"
  },
  {
    "code_dpto":"5",
    "code":"5664",
    "name":"SAN PEDRO"
  },
  {
    "code_dpto":"5",
    "code":"5665",
    "name":"SAN PEDRO DE URABA"
  },
  {
    "code_dpto":"5",
    "code":"5667",
    "name":"SAN RAFAEL"
  },
  {
    "code_dpto":"5",
    "code":"5670",
    "name":"SAN ROQUE"
  },
  {
    "code_dpto":"5",
    "code":"5674",
    "name":"SAN VICENTE"
  },
  {
    "code_dpto":"5",
    "code":"5679",
    "name":"SANTA BÁRBARA"
  },
  {
    "code_dpto":"5",
    "code":"5686",
    "name":"SANTA ROSA DE OSOS"
  },
  {
    "code_dpto":"5",
    "code":"5690",
    "name":"SANTO DOMINGO"
  },
  {
    "code_dpto":"5",
    "code":"5697",
    "name":"EL SANTUARIO"
  },
  {
    "code_dpto":"5",
    "code":"5736",
    "name":"SEGOVIA"
  },
  {
    "code_dpto":"5",
    "code":"5756",
    "name":"SONSON"
  },
  {
    "code_dpto":"5",
    "code":"5761",
    "name":"SOPETRÁN"
  },
  {
    "code_dpto":"5",
    "code":"5789",
    "name":"TÁMESIS"
  },
  {
    "code_dpto":"5",
    "code":"5790",
    "name":"TARAZÁ"
  },
  {
    "code_dpto":"5",
    "code":"5792",
    "name":"TARSO"
  },
  {
    "code_dpto":"5",
    "code":"5809",
    "name":"TITIRIBÍ"
  },
  {
    "code_dpto":"5",
    "code":"5819",
    "name":"TOLEDO"
  },
  {
    "code_dpto":"5",
    "code":"5837",
    "name":"TURBO"
  },
  {
    "code_dpto":"5",
    "code":"5842",
    "name":"URAMITA"
  },
  {
    "code_dpto":"5",
    "code":"5847",
    "name":"URRAO"
  },
  {
    "code_dpto":"5",
    "code":"5854",
    "name":"VALDIVIA"
  },
  {
    "code_dpto":"5",
    "code":"5856",
    "name":"VALPARAÍSO"
  },
  {
    "code_dpto":"5",
    "code":"5858",
    "name":"VEGACHÍ"
  },
  {
    "code_dpto":"5",
    "code":"5861",
    "name":"VENECIA"
  },
  {
    "code_dpto":"5",
    "code":"5873",
    "name":"VIGÍA DEL FUERTE"
  },
  {
    "code_dpto":"5",
    "code":"5885",
    "name":"YALÍ"
  },
  {
    "code_dpto":"5",
    "code":"5887",
    "name":"YARUMAL"
  },
  {
    "code_dpto":"5",
    "code":"5890",
    "name":"YOLOMBÓ"
  },
  {
    "code_dpto":"5",
    "code":"5893",
    "name":"YONDÓ"
  },
  {
    "code_dpto":"5",
    "code":"5895",
    "name":"ZARAGOZA"
  },
  {
    "code_dpto":"8",
    "code":"8001",
    "name":"BARRANQUILLA"
  },
  {
    "code_dpto":"8",
    "code":"8078",
    "name":"BARANOA"
  },
  {
    "code_dpto":"8",
    "code":"8137",
    "name":"CAMPO DE LA CRUZ"
  },
  {
    "code_dpto":"8",
    "code":"8141",
    "name":"CANDELARIA"
  },
  {
    "code_dpto":"8",
    "code":"8296",
    "name":"GALAPA"
  },
  {
    "code_dpto":"8",
    "code":"8372",
    "name":"JUAN DE ACOSTA"
  },
  {
    "code_dpto":"8",
    "code":"8421",
    "name":"LURUACO"
  },
  {
    "code_dpto":"8",
    "code":"8433",
    "name":"MALAMBO"
  },
  {
    "code_dpto":"8",
    "code":"8436",
    "name":"MANATÍ"
  },
  {
    "code_dpto":"8",
    "code":"8520",
    "name":"PALMAR DE VARELA"
  },
  {
    "code_dpto":"8",
    "code":"8549",
    "name":"PIOJÓ"
  },
  {
    "code_dpto":"8",
    "code":"8558",
    "name":"POLONUEVO"
  },
  {
    "code_dpto":"8",
    "code":"8560",
    "name":"PONEDERA"
  },
  {
    "code_dpto":"8",
    "code":"8573",
    "name":"PUERTO COLOMBIA"
  },
  {
    "code_dpto":"8",
    "code":"8606",
    "name":"REPELÓN"
  },
  {
    "code_dpto":"8",
    "code":"8634",
    "name":"SABANAGRANDE"
  },
  {
    "code_dpto":"8",
    "code":"8638",
    "name":"SABANALARGA"
  },
  {
    "code_dpto":"8",
    "code":"8675",
    "name":"SANTA LUCÍA"
  },
  {
    "code_dpto":"8",
    "code":"8685",
    "name":"SANTO TOMÁS"
  },
  {
    "code_dpto":"8",
    "code":"8758",
    "name":"SOLEDAD"
  },
  {
    "code_dpto":"8",
    "code":"8770",
    "name":"SUAN"
  },
  {
    "code_dpto":"8",
    "code":"8832",
    "name":"TUBARÁ"
  },
  {
    "code_dpto":"8",
    "code":"8849",
    "name":"USIACURÍ"
  },
  {
    "code_dpto":"11",
    "code":"11001",
    "name":"BOGOTÁ"
  },
  {
    "code_dpto":"13",
    "code":"13001",
    "name":"CARTAGENA"
  },
  {
    "code_dpto":"13",
    "code":"13006",
    "name":"ACHÍ"
  },
  {
    "code_dpto":"13",
    "code":"13030",
    "name":"ALTOS DEL ROSARIO"
  },
  {
    "code_dpto":"13",
    "code":"13042",
    "name":"ARENAL"
  },
  {
    "code_dpto":"13",
    "code":"13052",
    "name":"ARJONA"
  },
  {
    "code_dpto":"13",
    "code":"13062",
    "name":"ARROYOHONDO"
  },
  {
    "code_dpto":"13",
    "code":"13074",
    "name":"BARRANCO DE LOBA"
  },
  {
    "code_dpto":"13",
    "code":"13140",
    "name":"CALAMAR"
  },
  {
    "code_dpto":"13",
    "code":"13160",
    "name":"CANTAGALLO"
  },
  {
    "code_dpto":"13",
    "code":"13188",
    "name":"CICUCO"
  },
  {
    "code_dpto":"13",
    "code":"13212",
    "name":"CÓRDOBA"
  },
  {
    "code_dpto":"13",
    "code":"13222",
    "name":"CLEMENCIA"
  },
  {
    "code_dpto":"13",
    "code":"13244",
    "name":"EL CARMEN DE BOLÍVAR"
  },
  {
    "code_dpto":"13",
    "code":"13248",
    "name":"EL GUAMO"
  },
  {
    "code_dpto":"13",
    "code":"13268",
    "name":"EL PEÑÓN"
  },
  {
    "code_dpto":"13",
    "code":"13300",
    "name":"HATILLO DE LOBA"
  },
  {
    "code_dpto":"13",
    "code":"13430",
    "name":"MAGANGUÉ"
  },
  {
    "code_dpto":"13",
    "code":"13433",
    "name":"MAHATES"
  },
  {
    "code_dpto":"13",
    "code":"13440",
    "name":"MARGARITA"
  },
  {
    "code_dpto":"13",
    "code":"13442",
    "name":"MARÍA LA BAJA"
  },
  {
    "code_dpto":"13",
    "code":"13458",
    "name":"MONTECRISTO"
  },
  {
    "code_dpto":"13",
    "code":"13468",
    "name":"MOMPÓS"
  },
  {
    "code_dpto":"13",
    "code":"13473",
    "name":"MORALES"
  },
  {
    "code_dpto":"13",
    "code":"13549",
    "name":"PINILLOS"
  },
  {
    "code_dpto":"13",
    "code":"13580",
    "name":"REGIDOR"
  },
  {
    "code_dpto":"13",
    "code":"13600",
    "name":"RÍO VIEJO"
  },
  {
    "code_dpto":"13",
    "code":"13620",
    "name":"SAN CRISTÓBAL"
  },
  {
    "code_dpto":"13",
    "code":"13647",
    "name":"SAN ESTANISLAO"
  },
  {
    "code_dpto":"13",
    "code":"13650",
    "name":"SAN FERNANDO"
  },
  {
    "code_dpto":"13",
    "code":"13654",
    "name":"SAN JACINTO"
  },
  {
    "code_dpto":"13",
    "code":"13655",
    "name":"SAN JACINTO DEL CAUCA"
  },
  {
    "code_dpto":"13",
    "code":"13657",
    "name":"SAN JUAN NEPOMUCENO"
  },
  {
    "code_dpto":"13",
    "code":"13667",
    "name":"SAN MARTÍN DE LOBA"
  },
  {
    "code_dpto":"13",
    "code":"13670",
    "name":"SAN PABLO"
  },
  {
    "code_dpto":"13",
    "code":"13673",
    "name":"SANTA CATALINA"
  },
  {
    "code_dpto":"13",
    "code":"13683",
    "name":"SANTA ROSA"
  },
  {
    "code_dpto":"13",
    "code":"13688",
    "name":"SANTA ROSA DEL SUR"
  },
  {
    "code_dpto":"13",
    "code":"13744",
    "name":"SIMITÍ"
  },
  {
    "code_dpto":"13",
    "code":"13760",
    "name":"SOPLAVIENTO"
  },
  {
    "code_dpto":"13",
    "code":"13780",
    "name":"TALAIGUA NUEVO"
  },
  {
    "code_dpto":"13",
    "code":"13810",
    "name":"TIQUISIO"
  },
  {
    "code_dpto":"13",
    "code":"13836",
    "name":"TURBACO"
  },
  {
    "code_dpto":"13",
    "code":"13838",
    "name":"TURBANÁ"
  },
  {
    "code_dpto":"13",
    "code":"13873",
    "name":"VILLANUEVA"
  },
  {
    "code_dpto":"13",
    "code":"13894",
    "name":"ZAMBRANO"
  },
  {
    "code_dpto":"15",
    "code":"15001",
    "name":"TUNJA"
  },
  {
    "code_dpto":"15",
    "code":"15022",
    "name":"ALMEIDA"
  },
  {
    "code_dpto":"15",
    "code":"15047",
    "name":"AQUITANIA"
  },
  {
    "code_dpto":"15",
    "code":"15051",
    "name":"ARCABUCO"
  },
  {
    "code_dpto":"15",
    "code":"15087",
    "name":"BELÉN"
  },
  {
    "code_dpto":"15",
    "code":"15090",
    "name":"BERBEO"
  },
  {
    "code_dpto":"15",
    "code":"15092",
    "name":"BETÉITIVA"
  },
  {
    "code_dpto":"15",
    "code":"15097",
    "name":"BOAVITA"
  },
  {
    "code_dpto":"15",
    "code":"15104",
    "name":"BOYACÁ"
  },
  {
    "code_dpto":"15",
    "code":"15106",
    "name":"BRICEÑO"
  },
  {
    "code_dpto":"15",
    "code":"15109",
    "name":"BUENAVISTA"
  },
  {
    "code_dpto":"15",
    "code":"15114",
    "name":"BUSBANZÁ"
  },
  {
    "code_dpto":"15",
    "code":"15131",
    "name":"CALDAS"
  },
  {
    "code_dpto":"15",
    "code":"15135",
    "name":"CAMPOHERMOSO"
  },
  {
    "code_dpto":"15",
    "code":"15162",
    "name":"CERINZA"
  },
  {
    "code_dpto":"15",
    "code":"15172",
    "name":"CHINAVITA"
  },
  {
    "code_dpto":"15",
    "code":"15176",
    "name":"CHIQUINQUIRÁ"
  },
  {
    "code_dpto":"15",
    "code":"15180",
    "name":"CHISCAS"
  },
  {
    "code_dpto":"15",
    "code":"15183",
    "name":"CHITA"
  },
  {
    "code_dpto":"15",
    "code":"15185",
    "name":"CHITARAQUE"
  },
  {
    "code_dpto":"15",
    "code":"15187",
    "name":"CHIVATÁ"
  },
  {
    "code_dpto":"15",
    "code":"15189",
    "name":"CIÉNEGA"
  },
  {
    "code_dpto":"15",
    "code":"15204",
    "name":"CÓMBITA"
  },
  {
    "code_dpto":"15",
    "code":"15212",
    "name":"COPER"
  },
  {
    "code_dpto":"15",
    "code":"15215",
    "name":"CORRALES"
  },
  {
    "code_dpto":"15",
    "code":"15218",
    "name":"COVARACHÍA"
  },
  {
    "code_dpto":"15",
    "code":"15223",
    "name":"CUBARÁ"
  },
  {
    "code_dpto":"15",
    "code":"15224",
    "name":"CUCAITA"
  },
  {
    "code_dpto":"15",
    "code":"15226",
    "name":"CUÍTIVA"
  },
  {
    "code_dpto":"15",
    "code":"15232",
    "name":"CHÍQUIZA"
  },
  {
    "code_dpto":"15",
    "code":"15236",
    "name":"CHIVOR"
  },
  {
    "code_dpto":"15",
    "code":"15238",
    "name":"DUITAMA"
  },
  {
    "code_dpto":"15",
    "code":"15244",
    "name":"EL COCUY"
  },
  {
    "code_dpto":"15",
    "code":"15248",
    "name":"EL ESPINO"
  },
  {
    "code_dpto":"15",
    "code":"15272",
    "name":"FIRAVITOBA"
  },
  {
    "code_dpto":"15",
    "code":"15276",
    "name":"FLORESTA"
  },
  {
    "code_dpto":"15",
    "code":"15293",
    "name":"GACHANTIVÁ"
  },
  {
    "code_dpto":"15",
    "code":"15296",
    "name":"GAMEZA"
  },
  {
    "code_dpto":"15",
    "code":"15299",
    "name":"GARAGOA"
  },
  {
    "code_dpto":"15",
    "code":"15317",
    "name":"GUACAMAYAS"
  },
  {
    "code_dpto":"15",
    "code":"15322",
    "name":"GUATEQUE"
  },
  {
    "code_dpto":"15",
    "code":"15325",
    "name":"GUAYATÁ"
  },
  {
    "code_dpto":"15",
    "code":"15332",
    "name":"GÜICÁN"
  },
  {
    "code_dpto":"15",
    "code":"15362",
    "name":"IZA"
  },
  {
    "code_dpto":"15",
    "code":"15367",
    "name":"JENESANO"
  },
  {
    "code_dpto":"15",
    "code":"15368",
    "name":"JERICÓ"
  },
  {
    "code_dpto":"15",
    "code":"15377",
    "name":"LABRANZAGRANDE"
  },
  {
    "code_dpto":"15",
    "code":"15380",
    "name":"LA CAPILLA"
  },
  {
    "code_dpto":"15",
    "code":"15401",
    "name":"LA VICTORIA"
  },
  {
    "code_dpto":"15",
    "code":"15403",
    "name":"LA UVITA"
  },
  {
    "code_dpto":"15",
    "code":"15407",
    "name":"VILLA DE LEYVA"
  },
  {
    "code_dpto":"15",
    "code":"15425",
    "name":"MACANAL"
  },
  {
    "code_dpto":"15",
    "code":"15442",
    "name":"MARIPÍ"
  },
  {
    "code_dpto":"15",
    "code":"15455",
    "name":"MIRAFLORES"
  },
  {
    "code_dpto":"15",
    "code":"15464",
    "name":"MONGUA"
  },
  {
    "code_dpto":"15",
    "code":"15466",
    "name":"MONGUÍ"
  },
  {
    "code_dpto":"15",
    "code":"15469",
    "name":"MONIQUIRÁ"
  },
  {
    "code_dpto":"15",
    "code":"15476",
    "name":"MOTAVITA"
  },
  {
    "code_dpto":"15",
    "code":"15480",
    "name":"MUZO"
  },
  {
    "code_dpto":"15",
    "code":"15491",
    "name":"NOBSA"
  },
  {
    "code_dpto":"15",
    "code":"15494",
    "name":"NUEVO COLÓN"
  },
  {
    "code_dpto":"15",
    "code":"15500",
    "name":"OICATÁ"
  },
  {
    "code_dpto":"15",
    "code":"15507",
    "name":"OTANCHE"
  },
  {
    "code_dpto":"15",
    "code":"15511",
    "name":"PACHAVITA"
  },
  {
    "code_dpto":"15",
    "code":"15514",
    "name":"PÁEZ"
  },
  {
    "code_dpto":"15",
    "code":"15516",
    "name":"PAIPA"
  },
  {
    "code_dpto":"15",
    "code":"15518",
    "name":"PAJARITO"
  },
  {
    "code_dpto":"15",
    "code":"15522",
    "name":"PANQUEBA"
  },
  {
    "code_dpto":"15",
    "code":"15531",
    "name":"PAUNA"
  },
  {
    "code_dpto":"15",
    "code":"15533",
    "name":"PAYA"
  },
  {
    "code_dpto":"15",
    "code":"15537",
    "name":"PAZ DE RÍO"
  },
  {
    "code_dpto":"15",
    "code":"15542",
    "name":"PESCA"
  },
  {
    "code_dpto":"15",
    "code":"15550",
    "name":"PISBA"
  },
  {
    "code_dpto":"15",
    "code":"15572",
    "name":"PUERTO BOYACÁ"
  },
  {
    "code_dpto":"15",
    "code":"15580",
    "name":"QUÍPAMA"
  },
  {
    "code_dpto":"15",
    "code":"15599",
    "name":"RAMIRIQUÍ"
  },
  {
    "code_dpto":"15",
    "code":"15600",
    "name":"RÁQUIRA"
  },
  {
    "code_dpto":"15",
    "code":"15621",
    "name":"RONDÓN"
  },
  {
    "code_dpto":"15",
    "code":"15632",
    "name":"SABOYÁ"
  },
  {
    "code_dpto":"15",
    "code":"15638",
    "name":"SÁCHICA"
  },
  {
    "code_dpto":"15",
    "code":"15646",
    "name":"SAMACÁ"
  },
  {
    "code_dpto":"15",
    "code":"15660",
    "name":"SAN EDUARDO"
  },
  {
    "code_dpto":"15",
    "code":"15664",
    "name":"SAN JOSÉ DE PARE"
  },
  {
    "code_dpto":"15",
    "code":"15667",
    "name":"SAN LUIS DE GACENO"
  },
  {
    "code_dpto":"15",
    "code":"15673",
    "name":"SAN MATEO"
  },
  {
    "code_dpto":"15",
    "code":"15676",
    "name":"SAN MIGUEL DE SEMA"
  },
  {
    "code_dpto":"15",
    "code":"15681",
    "name":"SAN PABLO DE BORBUR"
  },
  {
    "code_dpto":"15",
    "code":"15686",
    "name":"SANTANA"
  },
  {
    "code_dpto":"15",
    "code":"15690",
    "name":"SANTA MARÍA"
  },
  {
    "code_dpto":"15",
    "code":"15693",
    "name":"SANTA ROSA DE VITERBO"
  },
  {
    "code_dpto":"15",
    "code":"15696",
    "name":"SANTA SOFÍA"
  },
  {
    "code_dpto":"15",
    "code":"15720",
    "name":"SATIVANORTE"
  },
  {
    "code_dpto":"15",
    "code":"15723",
    "name":"SATIVASUR"
  },
  {
    "code_dpto":"15",
    "code":"15740",
    "name":"SIACHOQUE"
  },
  {
    "code_dpto":"15",
    "code":"15753",
    "name":"SOATÁ"
  },
  {
    "code_dpto":"15",
    "code":"15755",
    "name":"SOCOTÁ"
  },
  {
    "code_dpto":"15",
    "code":"15757",
    "name":"SOCHA"
  },
  {
    "code_dpto":"15",
    "code":"15759",
    "name":"SOGAMOSO"
  },
  {
    "code_dpto":"15",
    "code":"15761",
    "name":"SOMONDOCO"
  },
  {
    "code_dpto":"15",
    "code":"15762",
    "name":"SORA"
  },
  {
    "code_dpto":"15",
    "code":"15763",
    "name":"SOTAQUIRÁ"
  },
  {
    "code_dpto":"15",
    "code":"15764",
    "name":"SORACÁ"
  },
  {
    "code_dpto":"15",
    "code":"15774",
    "name":"SUSACÓN"
  },
  {
    "code_dpto":"15",
    "code":"15776",
    "name":"SUTAMARCHÁN"
  },
  {
    "code_dpto":"15",
    "code":"15778",
    "name":"SUTATENZA"
  },
  {
    "code_dpto":"15",
    "code":"15790",
    "name":"TASCO"
  },
  {
    "code_dpto":"15",
    "code":"15798",
    "name":"TENZA"
  },
  {
    "code_dpto":"15",
    "code":"15804",
    "name":"TIBANÁ"
  },
  {
    "code_dpto":"15",
    "code":"15806",
    "name":"TIBASOSA"
  },
  {
    "code_dpto":"15",
    "code":"15808",
    "name":"TINJACÁ"
  },
  {
    "code_dpto":"15",
    "code":"15810",
    "name":"TIPACOQUE"
  },
  {
    "code_dpto":"15",
    "code":"15814",
    "name":"TOCA"
  },
  {
    "code_dpto":"15",
    "code":"15816",
    "name":"TOGÜÍ"
  },
  {
    "code_dpto":"15",
    "code":"15820",
    "name":"TÓPAGA"
  },
  {
    "code_dpto":"15",
    "code":"15822",
    "name":"TOTA"
  },
  {
    "code_dpto":"15",
    "code":"15832",
    "name":"TUNUNGUÁ"
  },
  {
    "code_dpto":"15",
    "code":"15835",
    "name":"TURMEQUÉ"
  },
  {
    "code_dpto":"15",
    "code":"15837",
    "name":"TUTA"
  },
  {
    "code_dpto":"15",
    "code":"15839",
    "name":"TUTAZÁ"
  },
  {
    "code_dpto":"15",
    "code":"15842",
    "name":"UMBITA"
  },
  {
    "code_dpto":"15",
    "code":"15861",
    "name":"VENTAQUEMADA"
  },
  {
    "code_dpto":"15",
    "code":"15879",
    "name":"VIRACACHÁ"
  },
  {
    "code_dpto":"15",
    "code":"15897",
    "name":"ZETAQUIRA"
  },
  {
    "code_dpto":"17",
    "code":"17001",
    "name":"MANIZALES"
  },
  {
    "code_dpto":"17",
    "code":"17013",
    "name":"AGUADAS"
  },
  {
    "code_dpto":"17",
    "code":"17042",
    "name":"ANSERMA"
  },
  {
    "code_dpto":"17",
    "code":"17050",
    "name":"ARANZAZU"
  },
  {
    "code_dpto":"17",
    "code":"17088",
    "name":"BELALCÁZAR"
  },
  {
    "code_dpto":"17",
    "code":"17174",
    "name":"CHINCHINÁ"
  },
  {
    "code_dpto":"17",
    "code":"17272",
    "name":"FILADELFIA"
  },
  {
    "code_dpto":"17",
    "code":"17380",
    "name":"LA DORADA"
  },
  {
    "code_dpto":"17",
    "code":"17388",
    "name":"LA MERCED"
  },
  {
    "code_dpto":"17",
    "code":"17433",
    "name":"MANZANARES"
  },
  {
    "code_dpto":"17",
    "code":"17442",
    "name":"MARMATO"
  },
  {
    "code_dpto":"17",
    "code":"17444",
    "name":"MARQUETALIA"
  },
  {
    "code_dpto":"17",
    "code":"17446",
    "name":"MARULANDA"
  },
  {
    "code_dpto":"17",
    "code":"17486",
    "name":"NEIRA"
  },
  {
    "code_dpto":"17",
    "code":"17495",
    "name":"NORCASIA"
  },
  {
    "code_dpto":"17",
    "code":"17513",
    "name":"PÁCORA"
  },
  {
    "code_dpto":"17",
    "code":"17524",
    "name":"PALESTINA"
  },
  {
    "code_dpto":"17",
    "code":"17541",
    "name":"PENSILVANIA"
  },
  {
    "code_dpto":"17",
    "code":"17614",
    "name":"RIOSUCIO"
  },
  {
    "code_dpto":"17",
    "code":"17616",
    "name":"RISARALDA"
  },
  {
    "code_dpto":"17",
    "code":"17653",
    "name":"SALAMINA"
  },
  {
    "code_dpto":"17",
    "code":"17662",
    "name":"SAMANÁ"
  },
  {
    "code_dpto":"17",
    "code":"17665",
    "name":"SAN JOSÉ"
  },
  {
    "code_dpto":"17",
    "code":"17777",
    "name":"SUPÍA"
  },
  {
    "code_dpto":"17",
    "code":"17867",
    "name":"VICTORIA"
  },
  {
    "code_dpto":"17",
    "code":"17873",
    "name":"VILLAMARÍA"
  },
  {
    "code_dpto":"17",
    "code":"17877",
    "name":"VITERBO"
  },
  {
    "code_dpto":"18",
    "code":"18001",
    "name":"FLORENCIA"
  },
  {
    "code_dpto":"18",
    "code":"18029",
    "name":"ALBANIA"
  },
  {
    "code_dpto":"18",
    "code":"18094",
    "name":"BELÉN DE LOS ANDAQUIES"
  },
  {
    "code_dpto":"18",
    "code":"18150",
    "name":"CARTAGENA DEL CHAIRÁ"
  },
  {
    "code_dpto":"18",
    "code":"18205",
    "name":"CURILLO"
  },
  {
    "code_dpto":"18",
    "code":"18247",
    "name":"EL DONCELLO"
  },
  {
    "code_dpto":"18",
    "code":"18256",
    "name":"EL PAUJIL"
  },
  {
    "code_dpto":"18",
    "code":"18410",
    "name":"LA MONTAÑITA"
  },
  {
    "code_dpto":"18",
    "code":"18460",
    "name":"MILÁN"
  },
  {
    "code_dpto":"18",
    "code":"18479",
    "name":"MORELIA"
  },
  {
    "code_dpto":"18",
    "code":"18592",
    "name":"PUERTO RICO"
  },
  {
    "code_dpto":"18",
    "code":"18610",
    "name":"SAN JOSÉ DEL FRAGUA"
  },
  {
    "code_dpto":"18",
    "code":"18753",
    "name":"SAN VICENTE DEL CAGUÁN"
  },
  {
    "code_dpto":"18",
    "code":"18756",
    "name":"SOLANO"
  },
  {
    "code_dpto":"18",
    "code":"18785",
    "name":"SOLITA"
  },
  {
    "code_dpto":"18",
    "code":"18860",
    "name":"VALPARAÍSO"
  },
  {
    "code_dpto":"19",
    "code":"19001",
    "name":"POPAYÁN"
  },
  {
    "code_dpto":"19",
    "code":"19022",
    "name":"ALMAGUER"
  },
  {
    "code_dpto":"19",
    "code":"19050",
    "name":"ARGELIA"
  },
  {
    "code_dpto":"19",
    "code":"19075",
    "name":"BALBOA"
  },
  {
    "code_dpto":"19",
    "code":"19100",
    "name":"BOLÍVAR"
  },
  {
    "code_dpto":"19",
    "code":"19110",
    "name":"BUENOS AIRES"
  },
  {
    "code_dpto":"19",
    "code":"19130",
    "name":"CAJIBÍO"
  },
  {
    "code_dpto":"19",
    "code":"19137",
    "name":"CALDONO"
  },
  {
    "code_dpto":"19",
    "code":"19142",
    "name":"CALOTO"
  },
  {
    "code_dpto":"19",
    "code":"19212",
    "name":"CORINTO"
  },
  {
    "code_dpto":"19",
    "code":"19256",
    "name":"EL TAMBO"
  },
  {
    "code_dpto":"19",
    "code":"19290",
    "name":"FLORENCIA"
  },
  {
    "code_dpto":"19",
    "code":"19318",
    "name":"GUAPI"
  },
  {
    "code_dpto":"19",
    "code":"19355",
    "name":"INZÁ"
  },
  {
    "code_dpto":"19",
    "code":"19364",
    "name":"JAMBALÓ"
  },
  {
    "code_dpto":"19",
    "code":"19392",
    "name":"LA SIERRA"
  },
  {
    "code_dpto":"19",
    "code":"19397",
    "name":"LA VEGA"
  },
  {
    "code_dpto":"19",
    "code":"19418",
    "name":"LÓPEZ"
  },
  {
    "code_dpto":"19",
    "code":"19450",
    "name":"MERCADERES"
  },
  {
    "code_dpto":"19",
    "code":"19455",
    "name":"MIRANDA"
  },
  {
    "code_dpto":"19",
    "code":"19473",
    "name":"MORALES"
  },
  {
    "code_dpto":"19",
    "code":"19513",
    "name":"PADILLA"
  },
  {
    "code_dpto":"19",
    "code":"19517",
    "name":"PAEZ"
  },
  {
    "code_dpto":"19",
    "code":"19532",
    "name":"PATÍA"
  },
  {
    "code_dpto":"19",
    "code":"19533",
    "name":"PIAMONTE"
  },
  {
    "code_dpto":"19",
    "code":"19548",
    "name":"PIENDAMÓ"
  },
  {
    "code_dpto":"19",
    "code":"19573",
    "name":"PUERTO TEJADA"
  },
  {
    "code_dpto":"19",
    "code":"19585",
    "name":"PURACÉ"
  },
  {
    "code_dpto":"19",
    "code":"19622",
    "name":"ROSAS"
  },
  {
    "code_dpto":"19",
    "code":"19693",
    "name":"SAN SEBASTIÁN"
  },
  {
    "code_dpto":"19",
    "code":"19698",
    "name":"SANTANDER DE QUILICHAO"
  },
  {
    "code_dpto":"19",
    "code":"19701",
    "name":"SANTA ROSA"
  },
  {
    "code_dpto":"19",
    "code":"19743",
    "name":"SILVIA"
  },
  {
    "code_dpto":"19",
    "code":"19760",
    "name":"SOTARA"
  },
  {
    "code_dpto":"19",
    "code":"19780",
    "name":"SUÁREZ"
  },
  {
    "code_dpto":"19",
    "code":"19785",
    "name":"SUCRE"
  },
  {
    "code_dpto":"19",
    "code":"19807",
    "name":"TIMBÍO"
  },
  {
    "code_dpto":"19",
    "code":"19809",
    "name":"TIMBIQUÍ"
  },
  {
    "code_dpto":"19",
    "code":"19821",
    "name":"TORIBIO"
  },
  {
    "code_dpto":"19",
    "code":"19824",
    "name":"TOTORÓ"
  },
  {
    "code_dpto":"19",
    "code":"19845",
    "name":"VILLA RICA"
  },
  {
    "code_dpto":"20",
    "code":"20001",
    "name":"VALLEDUPAR"
  },
  {
    "code_dpto":"20",
    "code":"20011",
    "name":"AGUACHICA"
  },
  {
    "code_dpto":"20",
    "code":"20013",
    "name":"AGUSTÍN CODAZZI"
  },
  {
    "code_dpto":"20",
    "code":"20032",
    "name":"ASTREA"
  },
  {
    "code_dpto":"20",
    "code":"20045",
    "name":"BECERRIL"
  },
  {
    "code_dpto":"20",
    "code":"20060",
    "name":"BOSCONIA"
  },
  {
    "code_dpto":"20",
    "code":"20175",
    "name":"CHIMICHAGUA"
  },
  {
    "code_dpto":"20",
    "code":"20178",
    "name":"CHIRIGUANÁ"
  },
  {
    "code_dpto":"20",
    "code":"20228",
    "name":"CURUMANÍ"
  },
  {
    "code_dpto":"20",
    "code":"20238",
    "name":"EL COPEY"
  },
  {
    "code_dpto":"20",
    "code":"20250",
    "name":"EL PASO"
  },
  {
    "code_dpto":"20",
    "code":"20295",
    "name":"GAMARRA"
  },
  {
    "code_dpto":"20",
    "code":"20310",
    "name":"GONZÁLEZ"
  },
  {
    "code_dpto":"20",
    "code":"20383",
    "name":"LA GLORIA"
  },
  {
    "code_dpto":"20",
    "code":"20400",
    "name":"LA JAGUA DE IBIRICO"
  },
  {
    "code_dpto":"20",
    "code":"20443",
    "name":"MANAURE"
  },
  {
    "code_dpto":"20",
    "code":"20517",
    "name":"PAILITAS"
  },
  {
    "code_dpto":"20",
    "code":"20550",
    "name":"PELAYA"
  },
  {
    "code_dpto":"20",
    "code":"20570",
    "name":"PUEBLO BELLO"
  },
  {
    "code_dpto":"20",
    "code":"20614",
    "name":"RÍO DE ORO"
  },
  {
    "code_dpto":"20",
    "code":"20621",
    "name":"LA PAZ"
  },
  {
    "code_dpto":"20",
    "code":"20710",
    "name":"SAN ALBERTO"
  },
  {
    "code_dpto":"20",
    "code":"20750",
    "name":"SAN DIEGO"
  },
  {
    "code_dpto":"20",
    "code":"20770",
    "name":"SAN MARTÍN"
  },
  {
    "code_dpto":"20",
    "code":"20787",
    "name":"TAMALAMEQUE"
  },
  {
    "code_dpto":"23",
    "code":"23001",
    "name":"MONTERÍA"
  },
  {
    "code_dpto":"23",
    "code":"23068",
    "name":"AYAPEL"
  },
  {
    "code_dpto":"23",
    "code":"23079",
    "name":"BUENAVISTA"
  },
  {
    "code_dpto":"23",
    "code":"23090",
    "name":"CANALETE"
  },
  {
    "code_dpto":"23",
    "code":"23162",
    "name":"CERETÉ"
  },
  {
    "code_dpto":"23",
    "code":"23168",
    "name":"CHIMÁ"
  },
  {
    "code_dpto":"23",
    "code":"23182",
    "name":"CHINÚ"
  },
  {
    "code_dpto":"23",
    "code":"23189",
    "name":"CIÉNAGA DE ORO"
  },
  {
    "code_dpto":"23",
    "code":"23300",
    "name":"COTORRA"
  },
  {
    "code_dpto":"23",
    "code":"23350",
    "name":"LA APARTADA"
  },
  {
    "code_dpto":"23",
    "code":"23417",
    "name":"LORICA"
  },
  {
    "code_dpto":"23",
    "code":"23419",
    "name":"LOS CÓRDOBAS"
  },
  {
    "code_dpto":"23",
    "code":"23464",
    "name":"MOMIL"
  },
  {
    "code_dpto":"23",
    "code":"23466",
    "name":"MONTELÍBANO"
  },
  {
    "code_dpto":"23",
    "code":"23500",
    "name":"MOÑITOS"
  },
  {
    "code_dpto":"23",
    "code":"23555",
    "name":"PLANETA RICA"
  },
  {
    "code_dpto":"23",
    "code":"23570",
    "name":"PUEBLO NUEVO"
  },
  {
    "code_dpto":"23",
    "code":"23574",
    "name":"PUERTO ESCONDIDO"
  },
  {
    "code_dpto":"23",
    "code":"23580",
    "name":"PUERTO LIBERTADOR"
  },
  {
    "code_dpto":"23",
    "code":"23586",
    "name":"PURÍSIMA"
  },
  {
    "code_dpto":"23",
    "code":"23660",
    "name":"SAHAGÚN"
  },
  {
    "code_dpto":"23",
    "code":"23670",
    "name":"SAN ANDRÉS SOTAVENTO"
  },
  {
    "code_dpto":"23",
    "code":"23672",
    "name":"SAN ANTERO"
  },
  {
    "code_dpto":"23",
    "code":"23675",
    "name":"SAN BERNARDO DEL VIENTO"
  },
  {
    "code_dpto":"23",
    "code":"23678",
    "name":"SAN CARLOS"
  },
  {
    "code_dpto":"23",
    "code":"23686",
    "name":"SAN PELAYO"
  },
  {
    "code_dpto":"23",
    "code":"23807",
    "name":"TIERRALTA"
  },
  {
    "code_dpto":"23",
    "code":"23855",
    "name":"VALENCIA"
  },
  {
    "code_dpto":"25",
    "code":"25001",
    "name":"AGUA DE DIOS"
  },
  {
    "code_dpto":"25",
    "code":"25019",
    "name":"ALBÁN"
  },
  {
    "code_dpto":"25",
    "code":"25035",
    "name":"ANAPOIMA"
  },
  {
    "code_dpto":"25",
    "code":"25040",
    "name":"ANOLAIMA"
  },
  {
    "code_dpto":"25",
    "code":"25053",
    "name":"ARBELÁEZ"
  },
  {
    "code_dpto":"25",
    "code":"25086",
    "name":"BELTRÁN"
  },
  {
    "code_dpto":"25",
    "code":"25095",
    "name":"BITUIMA"
  },
  {
    "code_dpto":"25",
    "code":"25099",
    "name":"BOJACÁ"
  },
  {
    "code_dpto":"25",
    "code":"25120",
    "name":"CABRERA"
  },
  {
    "code_dpto":"25",
    "code":"25123",
    "name":"CACHIPAY"
  },
  {
    "code_dpto":"25",
    "code":"25126",
    "name":"CAJICÁ"
  },
  {
    "code_dpto":"25",
    "code":"25148",
    "name":"CAPARRAPÍ"
  },
  {
    "code_dpto":"25",
    "code":"25151",
    "name":"CAQUEZA"
  },
  {
    "code_dpto":"25",
    "code":"25154",
    "name":"CARMEN DE CARUPA"
  },
  {
    "code_dpto":"25",
    "code":"25168",
    "name":"CHAGUANÍ"
  },
  {
    "code_dpto":"25",
    "code":"25175",
    "name":"CHÍA"
  },
  {
    "code_dpto":"25",
    "code":"25178",
    "name":"CHIPAQUE"
  },
  {
    "code_dpto":"25",
    "code":"25181",
    "name":"CHOACHÍ"
  },
  {
    "code_dpto":"25",
    "code":"25183",
    "name":"CHOCONTÁ"
  },
  {
    "code_dpto":"25",
    "code":"25200",
    "name":"COGUA"
  },
  {
    "code_dpto":"25",
    "code":"25214",
    "name":"COTA"
  },
  {
    "code_dpto":"25",
    "code":"25224",
    "name":"CUCUNUBÁ"
  },
  {
    "code_dpto":"25",
    "code":"25245",
    "name":"EL COLEGIO"
  },
  {
    "code_dpto":"25",
    "code":"25258",
    "name":"EL PEÑÓN"
  },
  {
    "code_dpto":"25",
    "code":"25260",
    "name":"EL ROSAL"
  },
  {
    "code_dpto":"25",
    "code":"25269",
    "name":"FACATATIVÁ"
  },
  {
    "code_dpto":"25",
    "code":"25279",
    "name":"FOMEQUE"
  },
  {
    "code_dpto":"25",
    "code":"25281",
    "name":"FOSCA"
  },
  {
    "code_dpto":"25",
    "code":"25286",
    "name":"FUNZA"
  },
  {
    "code_dpto":"25",
    "code":"25288",
    "name":"FÚQUENE"
  },
  {
    "code_dpto":"25",
    "code":"25290",
    "name":"FUSAGASUGÁ"
  },
  {
    "code_dpto":"25",
    "code":"25293",
    "name":"GACHALA"
  },
  {
    "code_dpto":"25",
    "code":"25295",
    "name":"GACHANCIPÁ"
  },
  {
    "code_dpto":"25",
    "code":"25297",
    "name":"GACHETÁ"
  },
  {
    "code_dpto":"25",
    "code":"25299",
    "name":"GAMA"
  },
  {
    "code_dpto":"25",
    "code":"25307",
    "name":"GIRARDOT"
  },
  {
    "code_dpto":"25",
    "code":"25312",
    "name":"GRANADA"
  },
  {
    "code_dpto":"25",
    "code":"25317",
    "name":"GUACHETÁ"
  },
  {
    "code_dpto":"25",
    "code":"25320",
    "name":"GUADUAS"
  },
  {
    "code_dpto":"25",
    "code":"25322",
    "name":"GUASCA"
  },
  {
    "code_dpto":"25",
    "code":"25324",
    "name":"GUATAQUÍ"
  },
  {
    "code_dpto":"25",
    "code":"25326",
    "name":"GUATAVITA"
  },
  {
    "code_dpto":"25",
    "code":"25328",
    "name":"GUAYABAL DE SIQUIMA"
  },
  {
    "code_dpto":"25",
    "code":"25335",
    "name":"GUAYABETAL"
  },
  {
    "code_dpto":"25",
    "code":"25339",
    "name":"GUTIÉRREZ"
  },
  {
    "code_dpto":"25",
    "code":"25368",
    "name":"JERUSALÉN"
  },
  {
    "code_dpto":"25",
    "code":"25372",
    "name":"JUNÍN"
  },
  {
    "code_dpto":"25",
    "code":"25377",
    "name":"LA CALERA"
  },
  {
    "code_dpto":"25",
    "code":"25386",
    "name":"LA MESA"
  },
  {
    "code_dpto":"25",
    "code":"25394",
    "name":"LA PALMA"
  },
  {
    "code_dpto":"25",
    "code":"25398",
    "name":"LA PEÑA"
  },
  {
    "code_dpto":"25",
    "code":"25402",
    "name":"LA VEGA"
  },
  {
    "code_dpto":"25",
    "code":"25407",
    "name":"LENGUAZAQUE"
  },
  {
    "code_dpto":"25",
    "code":"25426",
    "name":"MACHETA"
  },
  {
    "code_dpto":"25",
    "code":"25430",
    "name":"MADRID"
  },
  {
    "code_dpto":"25",
    "code":"25436",
    "name":"MANTA"
  },
  {
    "code_dpto":"25",
    "code":"25438",
    "name":"MEDINA"
  },
  {
    "code_dpto":"25",
    "code":"25473",
    "name":"MOSQUERA"
  },
  {
    "code_dpto":"25",
    "code":"25483",
    "name":"NARIÑO"
  },
  {
    "code_dpto":"25",
    "code":"25486",
    "name":"NEMOCÓN"
  },
  {
    "code_dpto":"25",
    "code":"25488",
    "name":"NILO"
  },
  {
    "code_dpto":"25",
    "code":"25489",
    "name":"NIMAIMA"
  },
  {
    "code_dpto":"25",
    "code":"25491",
    "name":"NOCAIMA"
  },
  {
    "code_dpto":"25",
    "code":"25506",
    "name":"VENECIA"
  },
  {
    "code_dpto":"25",
    "code":"25513",
    "name":"PACHO"
  },
  {
    "code_dpto":"25",
    "code":"25518",
    "name":"PAIME"
  },
  {
    "code_dpto":"25",
    "code":"25524",
    "name":"PANDI"
  },
  {
    "code_dpto":"25",
    "code":"25530",
    "name":"PARATEBUENO"
  },
  {
    "code_dpto":"25",
    "code":"25535",
    "name":"PASCA"
  },
  {
    "code_dpto":"25",
    "code":"25572",
    "name":"PUERTO SALGAR"
  },
  {
    "code_dpto":"25",
    "code":"25580",
    "name":"PULÍ"
  },
  {
    "code_dpto":"25",
    "code":"25592",
    "name":"QUEBRADANEGRA"
  },
  {
    "code_dpto":"25",
    "code":"25594",
    "name":"QUETAME"
  },
  {
    "code_dpto":"25",
    "code":"25596",
    "name":"QUIPILE"
  },
  {
    "code_dpto":"25",
    "code":"25599",
    "name":"APULO"
  },
  {
    "code_dpto":"25",
    "code":"25612",
    "name":"RICAURTE"
  },
  {
    "code_dpto":"25",
    "code":"25645",
    "name":"SAN ANTONIO DEL TEQUENDAMA"
  },
  {
    "code_dpto":"25",
    "code":"25649",
    "name":"SAN BERNARDO"
  },
  {
    "code_dpto":"25",
    "code":"25653",
    "name":"SAN CAYETANO"
  },
  {
    "code_dpto":"25",
    "code":"25658",
    "name":"SAN FRANCISCO"
  },
  {
    "code_dpto":"25",
    "code":"25662",
    "name":"SAN JUAN DE RÍO SECO"
  },
  {
    "code_dpto":"25",
    "code":"25718",
    "name":"SASAIMA"
  },
  {
    "code_dpto":"25",
    "code":"25736",
    "name":"SESQUILÉ"
  },
  {
    "code_dpto":"25",
    "code":"25740",
    "name":"SIBATÉ"
  },
  {
    "code_dpto":"25",
    "code":"25743",
    "name":"SILVANIA"
  },
  {
    "code_dpto":"25",
    "code":"25745",
    "name":"SIMIJACA"
  },
  {
    "code_dpto":"25",
    "code":"25754",
    "name":"SOACHA"
  },
  {
    "code_dpto":"25",
    "code":"25758",
    "name":"SOPÓ"
  },
  {
    "code_dpto":"25",
    "code":"25769",
    "name":"SUBACHOQUE"
  },
  {
    "code_dpto":"25",
    "code":"25772",
    "name":"SUESCA"
  },
  {
    "code_dpto":"25",
    "code":"25777",
    "name":"SUPATÁ"
  },
  {
    "code_dpto":"25",
    "code":"25779",
    "name":"SUSA"
  },
  {
    "code_dpto":"25",
    "code":"25781",
    "name":"SUTATAUSA"
  },
  {
    "code_dpto":"25",
    "code":"25785",
    "name":"TABIO"
  },
  {
    "code_dpto":"25",
    "code":"25793",
    "name":"TAUSA"
  },
  {
    "code_dpto":"25",
    "code":"25797",
    "name":"TENA"
  },
  {
    "code_dpto":"25",
    "code":"25799",
    "name":"TENJO"
  },
  {
    "code_dpto":"25",
    "code":"25805",
    "name":"TIBACUY"
  },
  {
    "code_dpto":"25",
    "code":"25807",
    "name":"TIBIRITA"
  },
  {
    "code_dpto":"25",
    "code":"25815",
    "name":"TOCAIMA"
  },
  {
    "code_dpto":"25",
    "code":"25817",
    "name":"TOCANCIPÁ"
  },
  {
    "code_dpto":"25",
    "code":"25823",
    "name":"TOPAIPÍ"
  },
  {
    "code_dpto":"25",
    "code":"25839",
    "name":"UBALÁ"
  },
  {
    "code_dpto":"25",
    "code":"25841",
    "name":"UBAQUE"
  },
  {
    "code_dpto":"25",
    "code":"25843",
    "name":"VILLA DE SAN DIEGO DE UBATE"
  },
  {
    "code_dpto":"25",
    "code":"25845",
    "name":"UNE"
  },
  {
    "code_dpto":"25",
    "code":"25851",
    "name":"ÚTICA"
  },
  {
    "code_dpto":"25",
    "code":"25862",
    "name":"VERGARA"
  },
  {
    "code_dpto":"25",
    "code":"25867",
    "name":"VIANÍ"
  },
  {
    "code_dpto":"25",
    "code":"25871",
    "name":"VILLAGÓMEZ"
  },
  {
    "code_dpto":"25",
    "code":"25873",
    "name":"VILLAPINZÓN"
  },
  {
    "code_dpto":"25",
    "code":"25875",
    "name":"VILLETA"
  },
  {
    "code_dpto":"25",
    "code":"25878",
    "name":"VIOTÁ"
  },
  {
    "code_dpto":"25",
    "code":"25885",
    "name":"YACOPÍ"
  },
  {
    "code_dpto":"25",
    "code":"25898",
    "name":"ZIPACÓN"
  },
  {
    "code_dpto":"25",
    "code":"25899",
    "name":"ZIPAQUIRÁ"
  },
  {
    "code_dpto":"27",
    "code":"27001",
    "name":"QUIBDÓ"
  },
  {
    "code_dpto":"27",
    "code":"27006",
    "name":"ACANDÍ"
  },
  {
    "code_dpto":"27",
    "code":"27025",
    "name":"ALTO BAUDO"
  },
  {
    "code_dpto":"27",
    "code":"27050",
    "name":"ATRATO"
  },
  {
    "code_dpto":"27",
    "code":"27073",
    "name":"BAGADÓ"
  },
  {
    "code_dpto":"27",
    "code":"27075",
    "name":"BAHÍA SOLANO"
  },
  {
    "code_dpto":"27",
    "code":"27077",
    "name":"BAJO BAUDÓ"
  },
  {
    "code_dpto":"27",
    "code":"27086",
    "name":"BELÉN DE BAJIRÁ"
  },
  {
    "code_dpto":"27",
    "code":"27099",
    "name":"BOJAYA"
  },
  {
    "code_dpto":"27",
    "code":"27135",
    "name":"EL CANTÓN DEL SAN PABLO"
  },
  {
    "code_dpto":"27",
    "code":"27150",
    "name":"CARMEN DEL DARIEN"
  },
  {
    "code_dpto":"27",
    "code":"27160",
    "name":"CÉRTEGUI"
  },
  {
    "code_dpto":"27",
    "code":"27205",
    "name":"CONDOTO"
  },
  {
    "code_dpto":"27",
    "code":"27245",
    "name":"EL CARMEN DE ATRATO"
  },
  {
    "code_dpto":"27",
    "code":"27250",
    "name":"EL LITORAL DEL SAN JUAN"
  },
  {
    "code_dpto":"27",
    "code":"27361",
    "name":"ISTMINA"
  },
  {
    "code_dpto":"27",
    "code":"27372",
    "name":"JURADÓ"
  },
  {
    "code_dpto":"27",
    "code":"27413",
    "name":"LLORÓ"
  },
  {
    "code_dpto":"27",
    "code":"27425",
    "name":"MEDIO ATRATO"
  },
  {
    "code_dpto":"27",
    "code":"27430",
    "name":"MEDIO BAUDÓ"
  },
  {
    "code_dpto":"27",
    "code":"27450",
    "name":"MEDIO SAN JUAN"
  },
  {
    "code_dpto":"27",
    "code":"27491",
    "name":"NÓVITA"
  },
  {
    "code_dpto":"27",
    "code":"27495",
    "name":"NUQUÍ"
  },
  {
    "code_dpto":"27",
    "code":"27580",
    "name":"RÍO IRO"
  },
  {
    "code_dpto":"27",
    "code":"27600",
    "name":"RÍO QUITO"
  },
  {
    "code_dpto":"27",
    "code":"27615",
    "name":"RIOSUCIO"
  },
  {
    "code_dpto":"27",
    "code":"27660",
    "name":"SAN JOSÉ DEL PALMAR"
  },
  {
    "code_dpto":"27",
    "code":"27745",
    "name":"SIPÍ"
  },
  {
    "code_dpto":"27",
    "code":"27787",
    "name":"TADÓ"
  },
  {
    "code_dpto":"27",
    "code":"27800",
    "name":"UNGUÍA"
  },
  {
    "code_dpto":"27",
    "code":"27810",
    "name":"UNIÓN PANAMERICANA"
  },
  {
    "code_dpto":"41",
    "code":"41001",
    "name":"NEIVA"
  },
  {
    "code_dpto":"41",
    "code":"41006",
    "name":"ACEVEDO"
  },
  {
    "code_dpto":"41",
    "code":"41013",
    "name":"AGRADO"
  },
  {
    "code_dpto":"41",
    "code":"41016",
    "name":"AIPE"
  },
  {
    "code_dpto":"41",
    "code":"41020",
    "name":"ALGECIRAS"
  },
  {
    "code_dpto":"41",
    "code":"41026",
    "name":"ALTAMIRA"
  },
  {
    "code_dpto":"41",
    "code":"41078",
    "name":"BARAYA"
  },
  {
    "code_dpto":"41",
    "code":"41132",
    "name":"CAMPOALEGRE"
  },
  {
    "code_dpto":"41",
    "code":"41206",
    "name":"COLOMBIA"
  },
  {
    "code_dpto":"41",
    "code":"41244",
    "name":"ELÍAS"
  },
  {
    "code_dpto":"41",
    "code":"41298",
    "name":"GARZÓN"
  },
  {
    "code_dpto":"41",
    "code":"41306",
    "name":"GIGANTE"
  },
  {
    "code_dpto":"41",
    "code":"41319",
    "name":"GUADALUPE"
  },
  {
    "code_dpto":"41",
    "code":"41349",
    "name":"HOBO"
  },
  {
    "code_dpto":"41",
    "code":"41357",
    "name":"IQUIRA"
  },
  {
    "code_dpto":"41",
    "code":"41359",
    "name":"ISNOS"
  },
  {
    "code_dpto":"41",
    "code":"41378",
    "name":"LA ARGENTINA"
  },
  {
    "code_dpto":"41",
    "code":"41396",
    "name":"LA PLATA"
  },
  {
    "code_dpto":"41",
    "code":"41483",
    "name":"NÁTAGA"
  },
  {
    "code_dpto":"41",
    "code":"41503",
    "name":"OPORAPA"
  },
  {
    "code_dpto":"41",
    "code":"41518",
    "name":"PAICOL"
  },
  {
    "code_dpto":"41",
    "code":"41524",
    "name":"PALERMO"
  },
  {
    "code_dpto":"41",
    "code":"41530",
    "name":"PALESTINA"
  },
  {
    "code_dpto":"41",
    "code":"41548",
    "name":"PITAL"
  },
  {
    "code_dpto":"41",
    "code":"41551",
    "name":"PITALITO"
  },
  {
    "code_dpto":"41",
    "code":"41615",
    "name":"RIVERA"
  },
  {
    "code_dpto":"41",
    "code":"41660",
    "name":"SALADOBLANCO"
  },
  {
    "code_dpto":"41",
    "code":"41668",
    "name":"SAN AGUSTÍN"
  },
  {
    "code_dpto":"41",
    "code":"41676",
    "name":"SANTA MARÍA"
  },
  {
    "code_dpto":"41",
    "code":"41770",
    "name":"SUAZA"
  },
  {
    "code_dpto":"41",
    "code":"41791",
    "name":"TARQUI"
  },
  {
    "code_dpto":"41",
    "code":"41797",
    "name":"TESALIA"
  },
  {
    "code_dpto":"41",
    "code":"41799",
    "name":"TELLO"
  },
  {
    "code_dpto":"41",
    "code":"41801",
    "name":"TERUEL"
  },
  {
    "code_dpto":"41",
    "code":"41807",
    "name":"TIMANÁ"
  },
  {
    "code_dpto":"41",
    "code":"41872",
    "name":"VILLAVIEJA"
  },
  {
    "code_dpto":"41",
    "code":"41885",
    "name":"YAGUARÁ"
  },
  {
    "code_dpto":"44",
    "code":"44001",
    "name":"RIOHACHA"
  },
  {
    "code_dpto":"44",
    "code":"44035",
    "name":"ALBANIA"
  },
  {
    "code_dpto":"44",
    "code":"44078",
    "name":"BARRANCAS"
  },
  {
    "code_dpto":"44",
    "code":"44090",
    "name":"DIBULLA"
  },
  {
    "code_dpto":"44",
    "code":"44098",
    "name":"DISTRACCIÓN"
  },
  {
    "code_dpto":"44",
    "code":"44110",
    "name":"EL MOLINO"
  },
  {
    "code_dpto":"44",
    "code":"44279",
    "name":"FONSECA"
  },
  {
    "code_dpto":"44",
    "code":"44378",
    "name":"HATONUEVO"
  },
  {
    "code_dpto":"44",
    "code":"44420",
    "name":"LA JAGUA DEL PILAR"
  },
  {
    "code_dpto":"44",
    "code":"44430",
    "name":"MAICAO"
  },
  {
    "code_dpto":"44",
    "code":"44560",
    "name":"MANAURE"
  },
  {
    "code_dpto":"44",
    "code":"44650",
    "name":"SAN JUAN DEL CESAR"
  },
  {
    "code_dpto":"44",
    "code":"44847",
    "name":"URIBIA"
  },
  {
    "code_dpto":"44",
    "code":"44855",
    "name":"URUMITA"
  },
  {
    "code_dpto":"44",
    "code":"44874",
    "name":"VILLANUEVA"
  },
  {
    "code_dpto":"47",
    "code":"47001",
    "name":"SANTA MARTA"
  },
  {
    "code_dpto":"47",
    "code":"47030",
    "name":"ALGARROBO"
  },
  {
    "code_dpto":"47",
    "code":"47053",
    "name":"ARACATACA"
  },
  {
    "code_dpto":"47",
    "code":"47058",
    "name":"ARIGUANÍ"
  },
  {
    "code_dpto":"47",
    "code":"47161",
    "name":"CERRO SAN ANTONIO"
  },
  {
    "code_dpto":"47",
    "code":"47170",
    "name":"CHIBOLO"
  },
  {
    "code_dpto":"47",
    "code":"47189",
    "name":"CIÉNAGA"
  },
  {
    "code_dpto":"47",
    "code":"47205",
    "name":"CONCORDIA"
  },
  {
    "code_dpto":"47",
    "code":"47245",
    "name":"EL BANCO"
  },
  {
    "code_dpto":"47",
    "code":"47258",
    "name":"EL PIÑON"
  },
  {
    "code_dpto":"47",
    "code":"47268",
    "name":"EL RETÉN"
  },
  {
    "code_dpto":"47",
    "code":"47288",
    "name":"FUNDACIÓN"
  },
  {
    "code_dpto":"47",
    "code":"47318",
    "name":"GUAMAL"
  },
  {
    "code_dpto":"47",
    "code":"47460",
    "name":"NUEVA GRANADA"
  },
  {
    "code_dpto":"47",
    "code":"47541",
    "name":"PEDRAZA"
  },
  {
    "code_dpto":"47",
    "code":"47545",
    "name":"PIJIÑO DEL CARMEN"
  },
  {
    "code_dpto":"47",
    "code":"47551",
    "name":"PIVIJAY"
  },
  {
    "code_dpto":"47",
    "code":"47555",
    "name":"PLATO"
  },
  {
    "code_dpto":"47",
    "code":"47570",
    "name":"PUEBLOVIEJO"
  },
  {
    "code_dpto":"47",
    "code":"47605",
    "name":"REMOLINO"
  },
  {
    "code_dpto":"47",
    "code":"47660",
    "name":"SABANAS DE SAN ANGEL"
  },
  {
    "code_dpto":"47",
    "code":"47675",
    "name":"SALAMINA"
  },
  {
    "code_dpto":"47",
    "code":"47692",
    "name":"SAN SEBASTIÁN DE BUENAVISTA"
  },
  {
    "code_dpto":"47",
    "code":"47703",
    "name":"SAN ZENÓN"
  },
  {
    "code_dpto":"47",
    "code":"47707",
    "name":"SANTA ANA"
  },
  {
    "code_dpto":"47",
    "code":"47720",
    "name":"SANTA BÁRBARA DE PINTO"
  },
  {
    "code_dpto":"47",
    "code":"47745",
    "name":"SITIONUEVO"
  },
  {
    "code_dpto":"47",
    "code":"47798",
    "name":"TENERIFE"
  },
  {
    "code_dpto":"47",
    "code":"47960",
    "name":"ZAPAYÁN"
  },
  {
    "code_dpto":"47",
    "code":"47980",
    "name":"ZONA BANANERA"
  },
  {
    "code_dpto":"50",
    "code":"50001",
    "name":"VILLAVICENCIO"
  },
  {
    "code_dpto":"50",
    "code":"50006",
    "name":"ACACÍAS"
  },
  {
    "code_dpto":"50",
    "code":"50110",
    "name":"BARRANCA DE UPÍA"
  },
  {
    "code_dpto":"50",
    "code":"50124",
    "name":"CABUYARO"
  },
  {
    "code_dpto":"50",
    "code":"50150",
    "name":"CASTILLA LA NUEVA"
  },
  {
    "code_dpto":"50",
    "code":"50223",
    "name":"CUBARRAL"
  },
  {
    "code_dpto":"50",
    "code":"50226",
    "name":"CUMARAL"
  },
  {
    "code_dpto":"50",
    "code":"50245",
    "name":"EL CALVARIO"
  },
  {
    "code_dpto":"50",
    "code":"50251",
    "name":"EL CASTILLO"
  },
  {
    "code_dpto":"50",
    "code":"50270",
    "name":"EL DORADO"
  },
  {
    "code_dpto":"50",
    "code":"50287",
    "name":"FUENTE DE ORO"
  },
  {
    "code_dpto":"50",
    "code":"50313",
    "name":"GRANADA"
  },
  {
    "code_dpto":"50",
    "code":"50318",
    "name":"GUAMAL"
  },
  {
    "code_dpto":"50",
    "code":"50325",
    "name":"MAPIRIPÁN"
  },
  {
    "code_dpto":"50",
    "code":"50330",
    "name":"MESETAS"
  },
  {
    "code_dpto":"50",
    "code":"50350",
    "name":"LA MACARENA"
  },
  {
    "code_dpto":"50",
    "code":"50370",
    "name":"URIBE"
  },
  {
    "code_dpto":"50",
    "code":"50400",
    "name":"LEJANÍAS"
  },
  {
    "code_dpto":"50",
    "code":"50450",
    "name":"PUERTO CONCORDIA"
  },
  {
    "code_dpto":"50",
    "code":"50568",
    "name":"PUERTO GAITÁN"
  },
  {
    "code_dpto":"50",
    "code":"50573",
    "name":"PUERTO LÓPEZ"
  },
  {
    "code_dpto":"50",
    "code":"50577",
    "name":"PUERTO LLERAS"
  },
  {
    "code_dpto":"50",
    "code":"50590",
    "name":"PUERTO RICO"
  },
  {
    "code_dpto":"50",
    "code":"50606",
    "name":"RESTREPO"
  },
  {
    "code_dpto":"50",
    "code":"50680",
    "name":"SAN CARLOS DE GUAROA"
  },
  {
    "code_dpto":"50",
    "code":"50683",
    "name":"SAN JUAN DE ARAMA"
  },
  {
    "code_dpto":"50",
    "code":"50686",
    "name":"SAN JUANITO"
  },
  {
    "code_dpto":"50",
    "code":"50689",
    "name":"SAN MARTÍN"
  },
  {
    "code_dpto":"50",
    "code":"50711",
    "name":"VISTAHERMOSA"
  },
  {
    "code_dpto":"52",
    "code":"52001",
    "name":"PASTO"
  },
  {
    "code_dpto":"52",
    "code":"52019",
    "name":"ALBÁN"
  },
  {
    "code_dpto":"52",
    "code":"52022",
    "name":"ALDANA"
  },
  {
    "code_dpto":"52",
    "code":"52036",
    "name":"ANCUYÁ"
  },
  {
    "code_dpto":"52",
    "code":"52051",
    "name":"ARBOLEDA"
  },
  {
    "code_dpto":"52",
    "code":"52079",
    "name":"BARBACOAS"
  },
  {
    "code_dpto":"52",
    "code":"52083",
    "name":"BELÉN"
  },
  {
    "code_dpto":"52",
    "code":"52110",
    "name":"BUESACO"
  },
  {
    "code_dpto":"52",
    "code":"52203",
    "name":"COLÓN"
  },
  {
    "code_dpto":"52",
    "code":"52207",
    "name":"CONSACA"
  },
  {
    "code_dpto":"52",
    "code":"52210",
    "name":"CONTADERO"
  },
  {
    "code_dpto":"52",
    "code":"52215",
    "name":"CÓRDOBA"
  },
  {
    "code_dpto":"52",
    "code":"52224",
    "name":"CUASPUD"
  },
  {
    "code_dpto":"52",
    "code":"52227",
    "name":"CUMBAL"
  },
  {
    "code_dpto":"52",
    "code":"52233",
    "name":"CUMBITARA"
  },
  {
    "code_dpto":"52",
    "code":"52240",
    "name":"CHACHAGÜÍ"
  },
  {
    "code_dpto":"52",
    "code":"52250",
    "name":"EL CHARCO"
  },
  {
    "code_dpto":"52",
    "code":"52254",
    "name":"EL PEÑOL"
  },
  {
    "code_dpto":"52",
    "code":"52256",
    "name":"EL ROSARIO"
  },
  {
    "code_dpto":"52",
    "code":"52258",
    "name":"EL TABLÓN DE GÓMEZ"
  },
  {
    "code_dpto":"52",
    "code":"52260",
    "name":"EL TAMBO"
  },
  {
    "code_dpto":"52",
    "code":"52287",
    "name":"FUNES"
  },
  {
    "code_dpto":"52",
    "code":"52317",
    "name":"GUACHUCAL"
  },
  {
    "code_dpto":"52",
    "code":"52320",
    "name":"GUAITARILLA"
  },
  {
    "code_dpto":"52",
    "code":"52323",
    "name":"GUALMATÁN"
  },
  {
    "code_dpto":"52",
    "code":"52352",
    "name":"ILES"
  },
  {
    "code_dpto":"52",
    "code":"52354",
    "name":"IMUÉS"
  },
  {
    "code_dpto":"52",
    "code":"52356",
    "name":"IPIALES"
  },
  {
    "code_dpto":"52",
    "code":"52378",
    "name":"LA CRUZ"
  },
  {
    "code_dpto":"52",
    "code":"52381",
    "name":"LA FLORIDA"
  },
  {
    "code_dpto":"52",
    "code":"52385",
    "name":"LA LLANADA"
  },
  {
    "code_dpto":"52",
    "code":"52390",
    "name":"LA TOLA"
  },
  {
    "code_dpto":"52",
    "code":"52399",
    "name":"LA UNIÓN"
  },
  {
    "code_dpto":"52",
    "code":"52405",
    "name":"LEIVA"
  },
  {
    "code_dpto":"52",
    "code":"52411",
    "name":"LINARES"
  },
  {
    "code_dpto":"52",
    "code":"52418",
    "name":"LOS ANDES"
  },
  {
    "code_dpto":"52",
    "code":"52427",
    "name":"MAGÜI"
  },
  {
    "code_dpto":"52",
    "code":"52435",
    "name":"MALLAMA"
  },
  {
    "code_dpto":"52",
    "code":"52473",
    "name":"MOSQUERA"
  },
  {
    "code_dpto":"52",
    "code":"52480",
    "name":"NARIÑO"
  },
  {
    "code_dpto":"52",
    "code":"52490",
    "name":"OLAYA HERRERA"
  },
  {
    "code_dpto":"52",
    "code":"52506",
    "name":"OSPINA"
  },
  {
    "code_dpto":"52",
    "code":"52520",
    "name":"FRANCISCO PIZARRO"
  },
  {
    "code_dpto":"52",
    "code":"52540",
    "name":"POLICARPA"
  },
  {
    "code_dpto":"52",
    "code":"52560",
    "name":"POTOSÍ"
  },
  {
    "code_dpto":"52",
    "code":"52565",
    "name":"PROVIDENCIA"
  },
  {
    "code_dpto":"52",
    "code":"52573",
    "name":"PUERRES"
  },
  {
    "code_dpto":"52",
    "code":"52585",
    "name":"PUPIALES"
  },
  {
    "code_dpto":"52",
    "code":"52612",
    "name":"RICAURTE"
  },
  {
    "code_dpto":"52",
    "code":"52621",
    "name":"ROBERTO PAYÁN"
  },
  {
    "code_dpto":"52",
    "code":"52678",
    "name":"SAMANIEGO"
  },
  {
    "code_dpto":"52",
    "code":"52683",
    "name":"SANDONÁ"
  },
  {
    "code_dpto":"52",
    "code":"52685",
    "name":"SAN BERNARDO"
  },
  {
    "code_dpto":"52",
    "code":"52687",
    "name":"SAN LORENZO"
  },
  {
    "code_dpto":"52",
    "code":"52693",
    "name":"SAN PABLO"
  },
  {
    "code_dpto":"52",
    "code":"52694",
    "name":"SAN PEDRO DE CARTAGO"
  },
  {
    "code_dpto":"52",
    "code":"52696",
    "name":"SANTA BÁRBARA"
  },
  {
    "code_dpto":"52",
    "code":"52699",
    "name":"SANTACRUZ"
  },
  {
    "code_dpto":"52",
    "code":"52720",
    "name":"SAPUYES"
  },
  {
    "code_dpto":"52",
    "code":"52786",
    "name":"TAMINANGO"
  },
  {
    "code_dpto":"52",
    "code":"52788",
    "name":"TANGUA"
  },
  {
    "code_dpto":"52",
    "code":"52835",
    "name":"TUMACO"
  },
  {
    "code_dpto":"52",
    "code":"52838",
    "name":"TÚQUERRES"
  },
  {
    "code_dpto":"52",
    "code":"52885",
    "name":"YACUANQUER"
  },
  {
    "code_dpto":"54",
    "code":"54001",
    "name":"CÚCUTA"
  },
  {
    "code_dpto":"54",
    "code":"54003",
    "name":"ABREGO"
  },
  {
    "code_dpto":"54",
    "code":"54051",
    "name":"ARBOLEDAS"
  },
  {
    "code_dpto":"54",
    "code":"54099",
    "name":"BOCHALEMA"
  },
  {
    "code_dpto":"54",
    "code":"54109",
    "name":"BUCARASICA"
  },
  {
    "code_dpto":"54",
    "code":"54125",
    "name":"CÁCOTA"
  },
  {
    "code_dpto":"54",
    "code":"54128",
    "name":"CACHIRÁ"
  },
  {
    "code_dpto":"54",
    "code":"54172",
    "name":"CHINÁCOTA"
  },
  {
    "code_dpto":"54",
    "code":"54174",
    "name":"CHITAGÁ"
  },
  {
    "code_dpto":"54",
    "code":"54206",
    "name":"CONVENCIÓN"
  },
  {
    "code_dpto":"54",
    "code":"54223",
    "name":"CUCUTILLA"
  },
  {
    "code_dpto":"54",
    "code":"54239",
    "name":"DURANIA"
  },
  {
    "code_dpto":"54",
    "code":"54245",
    "name":"EL CARMEN"
  },
  {
    "code_dpto":"54",
    "code":"54250",
    "name":"EL TARRA"
  },
  {
    "code_dpto":"54",
    "code":"54261",
    "name":"EL ZULIA"
  },
  {
    "code_dpto":"54",
    "code":"54313",
    "name":"GRAMALOTE"
  },
  {
    "code_dpto":"54",
    "code":"54344",
    "name":"HACARÍ"
  },
  {
    "code_dpto":"54",
    "code":"54347",
    "name":"HERRÁN"
  },
  {
    "code_dpto":"54",
    "code":"54377",
    "name":"LABATECA"
  },
  {
    "code_dpto":"54",
    "code":"54385",
    "name":"LA ESPERANZA"
  },
  {
    "code_dpto":"54",
    "code":"54398",
    "name":"LA PLAYA"
  },
  {
    "code_dpto":"54",
    "code":"54405",
    "name":"LOS PATIOS"
  },
  {
    "code_dpto":"54",
    "code":"54418",
    "name":"LOURDES"
  },
  {
    "code_dpto":"54",
    "code":"54480",
    "name":"MUTISCUA"
  },
  {
    "code_dpto":"54",
    "code":"54498",
    "name":"OCAÑA"
  },
  {
    "code_dpto":"54",
    "code":"54518",
    "name":"PAMPLONA"
  },
  {
    "code_dpto":"54",
    "code":"54520",
    "name":"PAMPLONITA"
  },
  {
    "code_dpto":"54",
    "code":"54553",
    "name":"PUERTO SANTANDER"
  },
  {
    "code_dpto":"54",
    "code":"54599",
    "name":"RAGONVALIA"
  },
  {
    "code_dpto":"54",
    "code":"54660",
    "name":"SALAZAR"
  },
  {
    "code_dpto":"54",
    "code":"54670",
    "name":"SAN CALIXTO"
  },
  {
    "code_dpto":"54",
    "code":"54673",
    "name":"SAN CAYETANO"
  },
  {
    "code_dpto":"54",
    "code":"54680",
    "name":"SANTIAGO"
  },
  {
    "code_dpto":"54",
    "code":"54720",
    "name":"SARDINATA"
  },
  {
    "code_dpto":"54",
    "code":"54743",
    "name":"SILOS"
  },
  {
    "code_dpto":"54",
    "code":"54800",
    "name":"TEORAMA"
  },
  {
    "code_dpto":"54",
    "code":"54810",
    "name":"TIBÚ"
  },
  {
    "code_dpto":"54",
    "code":"54820",
    "name":"TOLEDO"
  },
  {
    "code_dpto":"54",
    "code":"54871",
    "name":"VILLA CARO"
  },
  {
    "code_dpto":"54",
    "code":"54874",
    "name":"VILLA DEL ROSARIO"
  },
  {
    "code_dpto":"63",
    "code":"63001",
    "name":"ARMENIA"
  },
  {
    "code_dpto":"63",
    "code":"63111",
    "name":"BUENAVISTA"
  },
  {
    "code_dpto":"63",
    "code":"63130",
    "name":"CALARCA"
  },
  {
    "code_dpto":"63",
    "code":"63190",
    "name":"CIRCASIA"
  },
  {
    "code_dpto":"63",
    "code":"63212",
    "name":"CÓRDOBA"
  },
  {
    "code_dpto":"63",
    "code":"63272",
    "name":"FILANDIA"
  },
  {
    "code_dpto":"63",
    "code":"63302",
    "name":"GÉNOVA"
  },
  {
    "code_dpto":"63",
    "code":"63401",
    "name":"LA TEBAIDA"
  },
  {
    "code_dpto":"63",
    "code":"63470",
    "name":"MONTENEGRO"
  },
  {
    "code_dpto":"63",
    "code":"63548",
    "name":"PIJAO"
  },
  {
    "code_dpto":"63",
    "code":"63594",
    "name":"QUIMBAYA"
  },
  {
    "code_dpto":"63",
    "code":"63690",
    "name":"SALENTO"
  },
  {
    "code_dpto":"66",
    "code":"66001",
    "name":"PEREIRA"
  },
  {
    "code_dpto":"66",
    "code":"66045",
    "name":"APÍA"
  },
  {
    "code_dpto":"66",
    "code":"66075",
    "name":"BALBOA"
  },
  {
    "code_dpto":"66",
    "code":"66088",
    "name":"BELÉN DE UMBRÍA"
  },
  {
    "code_dpto":"66",
    "code":"66170",
    "name":"DOSQUEBRADAS"
  },
  {
    "code_dpto":"66",
    "code":"66318",
    "name":"GUÁTICA"
  },
  {
    "code_dpto":"66",
    "code":"66383",
    "name":"LA CELIA"
  },
  {
    "code_dpto":"66",
    "code":"66400",
    "name":"LA VIRGINIA"
  },
  {
    "code_dpto":"66",
    "code":"66440",
    "name":"MARSELLA"
  },
  {
    "code_dpto":"66",
    "code":"66456",
    "name":"MISTRATÓ"
  },
  {
    "code_dpto":"66",
    "code":"66572",
    "name":"PUEBLO RICO"
  },
  {
    "code_dpto":"66",
    "code":"66594",
    "name":"QUINCHÍA"
  },
  {
    "code_dpto":"66",
    "code":"66682",
    "name":"SANTA ROSA DE CABAL"
  },
  {
    "code_dpto":"66",
    "code":"66687",
    "name":"SANTUARIO"
  },
  {
    "code_dpto":"68",
    "code":"68001",
    "name":"BUCARAMANGA"
  },
  {
    "code_dpto":"68",
    "code":"68013",
    "name":"AGUADA"
  },
  {
    "code_dpto":"68",
    "code":"68020",
    "name":"ALBANIA"
  },
  {
    "code_dpto":"68",
    "code":"68051",
    "name":"ARATOCA"
  },
  {
    "code_dpto":"68",
    "code":"68077",
    "name":"BARBOSA"
  },
  {
    "code_dpto":"68",
    "code":"68079",
    "name":"BARICHARA"
  },
  {
    "code_dpto":"68",
    "code":"68081",
    "name":"BARRANCABERMEJA"
  },
  {
    "code_dpto":"68",
    "code":"68092",
    "name":"BETULIA"
  },
  {
    "code_dpto":"68",
    "code":"68101",
    "name":"BOLÍVAR"
  },
  {
    "code_dpto":"68",
    "code":"68121",
    "name":"CABRERA"
  },
  {
    "code_dpto":"68",
    "code":"68132",
    "name":"CALIFORNIA"
  },
  {
    "code_dpto":"68",
    "code":"68147",
    "name":"CAPITANEJO"
  },
  {
    "code_dpto":"68",
    "code":"68152",
    "name":"CARCASÍ"
  },
  {
    "code_dpto":"68",
    "code":"68160",
    "name":"CEPITÁ"
  },
  {
    "code_dpto":"68",
    "code":"68162",
    "name":"CERRITO"
  },
  {
    "code_dpto":"68",
    "code":"68167",
    "name":"CHARALÁ"
  },
  {
    "code_dpto":"68",
    "code":"68169",
    "name":"CHARTA"
  },
  {
    "code_dpto":"68",
    "code":"68176",
    "name":"CHIMA"
  },
  {
    "code_dpto":"68",
    "code":"68179",
    "name":"CHIPATÁ"
  },
  {
    "code_dpto":"68",
    "code":"68190",
    "name":"CIMITARRA"
  },
  {
    "code_dpto":"68",
    "code":"68207",
    "name":"CONCEPCIÓN"
  },
  {
    "code_dpto":"68",
    "code":"68209",
    "name":"CONFINES"
  },
  {
    "code_dpto":"68",
    "code":"68211",
    "name":"CONTRATACIÓN"
  },
  {
    "code_dpto":"68",
    "code":"68217",
    "name":"COROMORO"
  },
  {
    "code_dpto":"68",
    "code":"68229",
    "name":"CURITÍ"
  },
  {
    "code_dpto":"68",
    "code":"68235",
    "name":"EL CARMEN DE CHUCURÍ"
  },
  {
    "code_dpto":"68",
    "code":"68245",
    "name":"EL GUACAMAYO"
  },
  {
    "code_dpto":"68",
    "code":"68250",
    "name":"EL PEÑÓN"
  },
  {
    "code_dpto":"68",
    "code":"68255",
    "name":"EL PLAYÓN"
  },
  {
    "code_dpto":"68",
    "code":"68264",
    "name":"ENCINO"
  },
  {
    "code_dpto":"68",
    "code":"68266",
    "name":"ENCISO"
  },
  {
    "code_dpto":"68",
    "code":"68271",
    "name":"FLORIÁN"
  },
  {
    "code_dpto":"68",
    "code":"68276",
    "name":"FLORIDABLANCA"
  },
  {
    "code_dpto":"68",
    "code":"68296",
    "name":"GALÁN"
  },
  {
    "code_dpto":"68",
    "code":"68298",
    "name":"GAMBITA"
  },
  {
    "code_dpto":"68",
    "code":"68307",
    "name":"GIRÓN"
  },
  {
    "code_dpto":"68",
    "code":"68318",
    "name":"GUACA"
  },
  {
    "code_dpto":"68",
    "code":"68320",
    "name":"GUADALUPE"
  },
  {
    "code_dpto":"68",
    "code":"68322",
    "name":"GUAPOTÁ"
  },
  {
    "code_dpto":"68",
    "code":"68324",
    "name":"GUAVATÁ"
  },
  {
    "code_dpto":"68",
    "code":"68327",
    "name":"GÜEPSA"
  },
  {
    "code_dpto":"68",
    "code":"68344",
    "name":"HATO"
  },
  {
    "code_dpto":"68",
    "code":"68368",
    "name":"JESÚS MARÍA"
  },
  {
    "code_dpto":"68",
    "code":"68370",
    "name":"JORDÁN"
  },
  {
    "code_dpto":"68",
    "code":"68377",
    "name":"LA BELLEZA"
  },
  {
    "code_dpto":"68",
    "code":"68385",
    "name":"LANDÁZURI"
  },
  {
    "code_dpto":"68",
    "code":"68397",
    "name":"LA PAZ"
  },
  {
    "code_dpto":"68",
    "code":"68406",
    "name":"LEBRÍJA"
  },
  {
    "code_dpto":"68",
    "code":"68418",
    "name":"LOS SANTOS"
  },
  {
    "code_dpto":"68",
    "code":"68425",
    "name":"MACARAVITA"
  },
  {
    "code_dpto":"68",
    "code":"68432",
    "name":"MÁLAGA"
  },
  {
    "code_dpto":"68",
    "code":"68444",
    "name":"MATANZA"
  },
  {
    "code_dpto":"68",
    "code":"68464",
    "name":"MOGOTES"
  },
  {
    "code_dpto":"68",
    "code":"68468",
    "name":"MOLAGAVITA"
  },
  {
    "code_dpto":"68",
    "code":"68498",
    "name":"OCAMONTE"
  },
  {
    "code_dpto":"68",
    "code":"68500",
    "name":"OIBA"
  },
  {
    "code_dpto":"68",
    "code":"68502",
    "name":"ONZAGA"
  },
  {
    "code_dpto":"68",
    "code":"68522",
    "name":"PALMAR"
  },
  {
    "code_dpto":"68",
    "code":"68524",
    "name":"PALMAS DEL SOCORRO"
  },
  {
    "code_dpto":"68",
    "code":"68533",
    "name":"PÁRAMO"
  },
  {
    "code_dpto":"68",
    "code":"68547",
    "name":"PIEDECUESTA"
  },
  {
    "code_dpto":"68",
    "code":"68549",
    "name":"PINCHOTE"
  },
  {
    "code_dpto":"68",
    "code":"68572",
    "name":"PUENTE NACIONAL"
  },
  {
    "code_dpto":"68",
    "code":"68573",
    "name":"PUERTO PARRA"
  },
  {
    "code_dpto":"68",
    "code":"68575",
    "name":"PUERTO WILCHES"
  },
  {
    "code_dpto":"68",
    "code":"68615",
    "name":"RIONEGRO"
  },
  {
    "code_dpto":"68",
    "code":"68655",
    "name":"SABANA DE TORRES"
  },
  {
    "code_dpto":"68",
    "code":"68669",
    "name":"SAN ANDRÉS"
  },
  {
    "code_dpto":"68",
    "code":"68673",
    "name":"SAN BENITO"
  },
  {
    "code_dpto":"68",
    "code":"68679",
    "name":"SAN GIL"
  },
  {
    "code_dpto":"68",
    "code":"68682",
    "name":"SAN JOAQUÍN"
  },
  {
    "code_dpto":"68",
    "code":"68684",
    "name":"SAN JOSÉ DE MIRANDA"
  },
  {
    "code_dpto":"68",
    "code":"68686",
    "name":"SAN MIGUEL"
  },
  {
    "code_dpto":"68",
    "code":"68689",
    "name":"SAN VICENTE DE CHUCURÍ"
  },
  {
    "code_dpto":"68",
    "code":"68705",
    "name":"SANTA BÁRBARA"
  },
  {
    "code_dpto":"68",
    "code":"68720",
    "name":"SANTA HELENA DEL OPÓN"
  },
  {
    "code_dpto":"68",
    "code":"68745",
    "name":"SIMACOTA"
  },
  {
    "code_dpto":"68",
    "code":"68755",
    "name":"SOCORRO"
  },
  {
    "code_dpto":"68",
    "code":"68770",
    "name":"SUAITA"
  },
  {
    "code_dpto":"68",
    "code":"68773",
    "name":"SUCRE"
  },
  {
    "code_dpto":"68",
    "code":"68780",
    "name":"SURATÁ"
  },
  {
    "code_dpto":"68",
    "code":"68820",
    "name":"TONA"
  },
  {
    "code_dpto":"68",
    "code":"68855",
    "name":"VALLE DE SAN JOSÉ"
  },
  {
    "code_dpto":"68",
    "code":"68861",
    "name":"VÉLEZ"
  },
  {
    "code_dpto":"68",
    "code":"68867",
    "name":"VETAS"
  },
  {
    "code_dpto":"68",
    "code":"68872",
    "name":"VILLANUEVA"
  },
  {
    "code_dpto":"68",
    "code":"68895",
    "name":"ZAPATOCA"
  },
  {
    "code_dpto":"70",
    "code":"70001",
    "name":"SINCELEJO"
  },
  {
    "code_dpto":"70",
    "code":"70110",
    "name":"BUENAVISTA"
  },
  {
    "code_dpto":"70",
    "code":"70124",
    "name":"CAIMITO"
  },
  {
    "code_dpto":"70",
    "code":"70204",
    "name":"COLOSO"
  },
  {
    "code_dpto":"70",
    "code":"70215",
    "name":"COROZAL"
  },
  {
    "code_dpto":"70",
    "code":"70221",
    "name":"COVEÑAS"
  },
  {
    "code_dpto":"70",
    "code":"70230",
    "name":"CHALÁN"
  },
  {
    "code_dpto":"70",
    "code":"70233",
    "name":"EL ROBLE"
  },
  {
    "code_dpto":"70",
    "code":"70235",
    "name":"GALERAS"
  },
  {
    "code_dpto":"70",
    "code":"70265",
    "name":"GUARANDA"
  },
  {
    "code_dpto":"70",
    "code":"70400",
    "name":"LA UNIÓN"
  },
  {
    "code_dpto":"70",
    "code":"70418",
    "name":"LOS PALMITOS"
  },
  {
    "code_dpto":"70",
    "code":"70429",
    "name":"MAJAGUAL"
  },
  {
    "code_dpto":"70",
    "code":"70473",
    "name":"MORROA"
  },
  {
    "code_dpto":"70",
    "code":"70508",
    "name":"OVEJAS"
  },
  {
    "code_dpto":"70",
    "code":"70523",
    "name":"PALMITO"
  },
  {
    "code_dpto":"70",
    "code":"70670",
    "name":"SAMPUÉS"
  },
  {
    "code_dpto":"70",
    "code":"70678",
    "name":"SAN BENITO ABAD"
  },
  {
    "code_dpto":"70",
    "code":"70702",
    "name":"SAN JUAN DE BETULIA"
  },
  {
    "code_dpto":"70",
    "code":"70708",
    "name":"SAN MARCOS"
  },
  {
    "code_dpto":"70",
    "code":"70713",
    "name":"SAN ONOFRE"
  },
  {
    "code_dpto":"70",
    "code":"70717",
    "name":"SAN PEDRO"
  },
  {
    "code_dpto":"70",
    "code":"70742",
    "name":"SAN LUIS DE SINCÉ"
  },
  {
    "code_dpto":"70",
    "code":"70771",
    "name":"SUCRE"
  },
  {
    "code_dpto":"70",
    "code":"70820",
    "name":"SANTIAGO DE TOLÚ"
  },
  {
    "code_dpto":"70",
    "code":"70823",
    "name":"TOLÚ VIEJO"
  },
  {
    "code_dpto":"73",
    "code":"73001",
    "name":"IBAGUÉ"
  },
  {
    "code_dpto":"73",
    "code":"73024",
    "name":"ALPUJARRA"
  },
  {
    "code_dpto":"73",
    "code":"73026",
    "name":"ALVARADO"
  },
  {
    "code_dpto":"73",
    "code":"73030",
    "name":"AMBALEMA"
  },
  {
    "code_dpto":"73",
    "code":"73043",
    "name":"ANZOÁTEGUI"
  },
  {
    "code_dpto":"73",
    "code":"73055",
    "name":"ARMERO"
  },
  {
    "code_dpto":"73",
    "code":"73067",
    "name":"ATACO"
  },
  {
    "code_dpto":"73",
    "code":"73124",
    "name":"CAJAMARCA"
  },
  {
    "code_dpto":"73",
    "code":"73148",
    "name":"CARMEN DE APICALÁ"
  },
  {
    "code_dpto":"73",
    "code":"73152",
    "name":"CASABIANCA"
  },
  {
    "code_dpto":"73",
    "code":"73168",
    "name":"CHAPARRAL"
  },
  {
    "code_dpto":"73",
    "code":"73200",
    "name":"COELLO"
  },
  {
    "code_dpto":"73",
    "code":"73217",
    "name":"COYAIMA"
  },
  {
    "code_dpto":"73",
    "code":"73226",
    "name":"CUNDAY"
  },
  {
    "code_dpto":"73",
    "code":"73236",
    "name":"DOLORES"
  },
  {
    "code_dpto":"73",
    "code":"73268",
    "name":"ESPINAL"
  },
  {
    "code_dpto":"73",
    "code":"73270",
    "name":"FALAN"
  },
  {
    "code_dpto":"73",
    "code":"73275",
    "name":"FLANDES"
  },
  {
    "code_dpto":"73",
    "code":"73283",
    "name":"FRESNO"
  },
  {
    "code_dpto":"73",
    "code":"73319",
    "name":"GUAMO"
  },
  {
    "code_dpto":"73",
    "code":"73347",
    "name":"HERVEO"
  },
  {
    "code_dpto":"73",
    "code":"73349",
    "name":"HONDA"
  },
  {
    "code_dpto":"73",
    "code":"73352",
    "name":"ICONONZO"
  },
  {
    "code_dpto":"73",
    "code":"73408",
    "name":"LÉRIDA"
  },
  {
    "code_dpto":"73",
    "code":"73411",
    "name":"LÍBANO"
  },
  {
    "code_dpto":"73",
    "code":"73443",
    "name":"MARIQUITA"
  },
  {
    "code_dpto":"73",
    "code":"73449",
    "name":"MELGAR"
  },
  {
    "code_dpto":"73",
    "code":"73461",
    "name":"MURILLO"
  },
  {
    "code_dpto":"73",
    "code":"73483",
    "name":"NATAGAIMA"
  },
  {
    "code_dpto":"73",
    "code":"73504",
    "name":"ORTEGA"
  },
  {
    "code_dpto":"73",
    "code":"73520",
    "name":"PALOCABILDO"
  },
  {
    "code_dpto":"73",
    "code":"73547",
    "name":"PIEDRAS"
  },
  {
    "code_dpto":"73",
    "code":"73555",
    "name":"PLANADAS"
  },
  {
    "code_dpto":"73",
    "code":"73563",
    "name":"PRADO"
  },
  {
    "code_dpto":"73",
    "code":"73585",
    "name":"PURIFICACIÓN"
  },
  {
    "code_dpto":"73",
    "code":"73616",
    "name":"RIOBLANCO"
  },
  {
    "code_dpto":"73",
    "code":"73622",
    "name":"RONCESVALLES"
  },
  {
    "code_dpto":"73",
    "code":"73624",
    "name":"ROVIRA"
  },
  {
    "code_dpto":"73",
    "code":"73671",
    "name":"SALDAÑA"
  },
  {
    "code_dpto":"73",
    "code":"73675",
    "name":"SAN ANTONIO"
  },
  {
    "code_dpto":"73",
    "code":"73678",
    "name":"SAN LUIS"
  },
  {
    "code_dpto":"73",
    "code":"73686",
    "name":"SANTA ISABEL"
  },
  {
    "code_dpto":"73",
    "code":"73770",
    "name":"SUÁREZ"
  },
  {
    "code_dpto":"73",
    "code":"73854",
    "name":"VALLE DE SAN JUAN"
  },
  {
    "code_dpto":"73",
    "code":"73861",
    "name":"VENADILLO"
  },
  {
    "code_dpto":"73",
    "code":"73870",
    "name":"VILLAHERMOSA"
  },
  {
    "code_dpto":"73",
    "code":"73873",
    "name":"VILLARRICA"
  },
  {
    "code_dpto":"76",
    "code":"76001",
    "name":"CALI"
  },
  {
    "code_dpto":"76",
    "code":"76020",
    "name":"ALCALÁ"
  },
  {
    "code_dpto":"76",
    "code":"76036",
    "name":"ANDALUCÍA"
  },
  {
    "code_dpto":"76",
    "code":"76041",
    "name":"ANSERMANUEVO"
  },
  {
    "code_dpto":"76",
    "code":"76054",
    "name":"ARGELIA"
  },
  {
    "code_dpto":"76",
    "code":"76100",
    "name":"BOLÍVAR"
  },
  {
    "code_dpto":"76",
    "code":"76109",
    "name":"BUENAVENTURA"
  },
  {
    "code_dpto":"76",
    "code":"76111",
    "name":"GUADALAJARA DE BUGA"
  },
  {
    "code_dpto":"76",
    "code":"76113",
    "name":"BUGALAGRANDE"
  },
  {
    "code_dpto":"76",
    "code":"76122",
    "name":"CAICEDONIA"
  },
  {
    "code_dpto":"76",
    "code":"76126",
    "name":"CALIMA"
  },
  {
    "code_dpto":"76",
    "code":"76130",
    "name":"CANDELARIA"
  },
  {
    "code_dpto":"76",
    "code":"76147",
    "name":"CARTAGO"
  },
  {
    "code_dpto":"76",
    "code":"76233",
    "name":"DAGUA"
  },
  {
    "code_dpto":"76",
    "code":"76243",
    "name":"EL ÁGUILA"
  },
  {
    "code_dpto":"76",
    "code":"76246",
    "name":"EL CAIRO"
  },
  {
    "code_dpto":"76",
    "code":"76248",
    "name":"EL CERRITO"
  },
  {
    "code_dpto":"76",
    "code":"76250",
    "name":"EL DOVIO"
  },
  {
    "code_dpto":"76",
    "code":"76275",
    "name":"FLORIDA"
  },
  {
    "code_dpto":"76",
    "code":"76306",
    "name":"GINEBRA"
  },
  {
    "code_dpto":"76",
    "code":"76318",
    "name":"GUACARÍ"
  },
  {
    "code_dpto":"76",
    "code":"76364",
    "name":"JAMUNDÍ"
  },
  {
    "code_dpto":"76",
    "code":"76377",
    "name":"LA CUMBRE"
  },
  {
    "code_dpto":"76",
    "code":"76400",
    "name":"LA UNIÓN"
  },
  {
    "code_dpto":"76",
    "code":"76403",
    "name":"LA VICTORIA"
  },
  {
    "code_dpto":"76",
    "code":"76497",
    "name":"OBANDO"
  },
  {
    "code_dpto":"76",
    "code":"76520",
    "name":"PALMIRA"
  },
  {
    "code_dpto":"76",
    "code":"76563",
    "name":"PRADERA"
  },
  {
    "code_dpto":"76",
    "code":"76606",
    "name":"RESTREPO"
  },
  {
    "code_dpto":"76",
    "code":"76616",
    "name":"RIOFRÍO"
  },
  {
    "code_dpto":"76",
    "code":"76622",
    "name":"ROLDANILLO"
  },
  {
    "code_dpto":"76",
    "code":"76670",
    "name":"SAN PEDRO"
  },
  {
    "code_dpto":"76",
    "code":"76736",
    "name":"SEVILLA"
  },
  {
    "code_dpto":"76",
    "code":"76823",
    "name":"TORO"
  },
  {
    "code_dpto":"76",
    "code":"76828",
    "name":"TRUJILLO"
  },
  {
    "code_dpto":"76",
    "code":"76834",
    "name":"TULUÁ"
  },
  {
    "code_dpto":"76",
    "code":"76845",
    "name":"ULLOA"
  },
  {
    "code_dpto":"76",
    "code":"76863",
    "name":"VERSALLES"
  },
  {
    "code_dpto":"76",
    "code":"76869",
    "name":"VIJES"
  },
  {
    "code_dpto":"76",
    "code":"76890",
    "name":"YOTOCO"
  },
  {
    "code_dpto":"76",
    "code":"76892",
    "name":"YUMBO"
  },
  {
    "code_dpto":"76",
    "code":"76895",
    "name":"ZARZAL"
  },
  {
    "code_dpto":"81",
    "code":"81001",
    "name":"ARAUCA"
  },
  {
    "code_dpto":"81",
    "code":"81065",
    "name":"ARAUQUITA"
  },
  {
    "code_dpto":"81",
    "code":"81220",
    "name":"CRAVO NORTE"
  },
  {
    "code_dpto":"81",
    "code":"81300",
    "name":"FORTUL"
  },
  {
    "code_dpto":"81",
    "code":"81591",
    "name":"PUERTO RONDÓN"
  },
  {
    "code_dpto":"81",
    "code":"81736",
    "name":"SARAVENA"
  },
  {
    "code_dpto":"81",
    "code":"81794",
    "name":"TAME"
  },
  {
    "code_dpto":"85",
    "code":"85001",
    "name":"YOPAL"
  },
  {
    "code_dpto":"85",
    "code":"85010",
    "name":"AGUAZUL"
  },
  {
    "code_dpto":"85",
    "code":"85015",
    "name":"CHAMEZA"
  },
  {
    "code_dpto":"85",
    "code":"85125",
    "name":"HATO COROZAL"
  },
  {
    "code_dpto":"85",
    "code":"85136",
    "name":"LA SALINA"
  },
  {
    "code_dpto":"85",
    "code":"85139",
    "name":"MANÍ"
  },
  {
    "code_dpto":"85",
    "code":"85162",
    "name":"MONTERREY"
  },
  {
    "code_dpto":"85",
    "code":"85225",
    "name":"NUNCHÍA"
  },
  {
    "code_dpto":"85",
    "code":"85230",
    "name":"OROCUÉ"
  },
  {
    "code_dpto":"85",
    "code":"85250",
    "name":"PAZ DE ARIPORO"
  },
  {
    "code_dpto":"85",
    "code":"85263",
    "name":"PORE"
  },
  {
    "code_dpto":"85",
    "code":"85279",
    "name":"RECETOR"
  },
  {
    "code_dpto":"85",
    "code":"85300",
    "name":"SABANALARGA"
  },
  {
    "code_dpto":"85",
    "code":"85315",
    "name":"SÁCAMA"
  },
  {
    "code_dpto":"85",
    "code":"85325",
    "name":"SAN LUIS DE PALENQUE"
  },
  {
    "code_dpto":"85",
    "code":"85400",
    "name":"TÁMARA"
  },
  {
    "code_dpto":"85",
    "code":"85410",
    "name":"TAURAMENA"
  },
  {
    "code_dpto":"85",
    "code":"85430",
    "name":"TRINIDAD"
  },
  {
    "code_dpto":"85",
    "code":"85440",
    "name":"VILLANUEVA"
  },
  {
    "code_dpto":"86",
    "code":"86001",
    "name":"MOCOA"
  },
  {
    "code_dpto":"86",
    "code":"86219",
    "name":"COLÓN"
  },
  {
    "code_dpto":"86",
    "code":"86320",
    "name":"ORITO"
  },
  {
    "code_dpto":"86",
    "code":"86568",
    "name":"PUERTO ASÍS"
  },
  {
    "code_dpto":"86",
    "code":"86569",
    "name":"PUERTO CAICEDO"
  },
  {
    "code_dpto":"86",
    "code":"86571",
    "name":"PUERTO GUZMÁN"
  },
  {
    "code_dpto":"86",
    "code":"86573",
    "name":"LEGUÍZAMO"
  },
  {
    "code_dpto":"86",
    "code":"86749",
    "name":"SIBUNDOY"
  },
  {
    "code_dpto":"86",
    "code":"86755",
    "name":"SAN FRANCISCO"
  },
  {
    "code_dpto":"86",
    "code":"86757",
    "name":"SAN MIGUEL"
  },
  {
    "code_dpto":"86",
    "code":"86760",
    "name":"SANTIAGO"
  },
  {
    "code_dpto":"86",
    "code":"86865",
    "name":"VALLE DEL GUAMUEZ"
  },
  {
    "code_dpto":"86",
    "code":"86885",
    "name":"VILLAGARZÓN"
  },
  {
    "code_dpto":"88",
    "code":"88001",
    "name":"SAN ANDRÉS"
  },
  {
    "code_dpto":"88",
    "code":"88564",
    "name":"PROVIDENCIA"
  },
  {
    "code_dpto":"91",
    "code":"91001",
    "name":"LETICIA"
  },
  {
    "code_dpto":"91",
    "code":"91263",
    "name":"EL ENCANTO"
  },
  {
    "code_dpto":"91",
    "code":"91405",
    "name":"LA CHORRERA"
  },
  {
    "code_dpto":"91",
    "code":"91407",
    "name":"LA PEDRERA"
  },
  {
    "code_dpto":"91",
    "code":"91430",
    "name":"LA VICTORIA"
  },
  {
    "code_dpto":"91",
    "code":"91460",
    "name":"MIRITI - PARANÁ"
  },
  {
    "code_dpto":"91",
    "code":"91530",
    "name":"PUERTO ALEGRÍA"
  },
  {
    "code_dpto":"91",
    "code":"91536",
    "name":"PUERTO ARICA"
  },
  {
    "code_dpto":"91",
    "code":"91540",
    "name":"PUERTO NARIÑO"
  },
  {
    "code_dpto":"91",
    "code":"91669",
    "name":"PUERTO SANTANDER"
  },
  {
    "code_dpto":"91",
    "code":"91798",
    "name":"TARAPACÁ"
  },
  {
    "code_dpto":"94",
    "code":"94001",
    "name":"INÍRIDA"
  },
  {
    "code_dpto":"94",
    "code":"94343",
    "name":"BARRANCO MINAS"
  },
  {
    "code_dpto":"94",
    "code":"94663",
    "name":"MAPIRIPANA"
  },
  {
    "code_dpto":"94",
    "code":"94883",
    "name":"SAN FELIPE"
  },
  {
    "code_dpto":"94",
    "code":"94884",
    "name":"PUERTO COLOMBIA"
  },
  {
    "code_dpto":"94",
    "code":"94885",
    "name":"LA GUADALUPE"
  },
  {
    "code_dpto":"94",
    "code":"94886",
    "name":"CACAHUAL"
  },
  {
    "code_dpto":"94",
    "code":"94887",
    "name":"PANA PANA"
  },
  {
    "code_dpto":"94",
    "code":"94888",
    "name":"MORICHAL"
  },
  {
    "code_dpto":"95",
    "code":"95001",
    "name":"SAN JOSÉ DEL GUAVIARE"
  },
  {
    "code_dpto":"95",
    "code":"95015",
    "name":"CALAMAR"
  },
  {
    "code_dpto":"95",
    "code":"95025",
    "name":"EL RETORNO"
  },
  {
    "code_dpto":"95",
    "code":"95200",
    "name":"MIRAFLORES"
  },
  {
    "code_dpto":"97",
    "code":"97001",
    "name":"MITÚ"
  },
  {
    "code_dpto":"97",
    "code":"97161",
    "name":"CARURU"
  },
  {
    "code_dpto":"97",
    "code":"97511",
    "name":"PACOA"
  },
  {
    "code_dpto":"97",
    "code":"97666",
    "name":"TARAIRA"
  },
  {
    "code_dpto":"97",
    "code":"97777",
    "name":"PAPUNAUA"
  },
  {
    "code_dpto":"97",
    "code":"97889",
    "name":"YAVARATÉ"
  },
  {
    "code_dpto":"99",
    "code":"99001",
    "name":"PUERTO CARREÑO"
  },
  {
    "code_dpto":"99",
    "code":"99524",
    "name":"LA PRIMAVERA"
  },
  {
    "code_dpto":"99",
    "code":"99624",
    "name":"SANTA ROSALÍA"
  },
  {
    "code_dpto":"99",
    "code":"99773",
    "name":"CUMARIBO"
  }
]